// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/lobby/end_game.proto
// Protobuf C++ Version: 6.32.1

#include "process/lobby/end_game.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Proto {

inline constexpr PayloadLobbyEndGameResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        success_{false} {}

template <typename>
PROTOBUF_CONSTEXPR PayloadLobbyEndGameResponse::PayloadLobbyEndGameResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PayloadLobbyEndGameResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PayloadLobbyEndGameResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadLobbyEndGameResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadLobbyEndGameResponseDefaultTypeInternal() {}
  union {
    PayloadLobbyEndGameResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadLobbyEndGameResponseDefaultTypeInternal _PayloadLobbyEndGameResponse_default_instance_;

inline constexpr PayloadLobbyEndGameRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        user_id_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR PayloadLobbyEndGameRequest::PayloadLobbyEndGameRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PayloadLobbyEndGameRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PayloadLobbyEndGameRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadLobbyEndGameRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadLobbyEndGameRequestDefaultTypeInternal() {}
  union {
    PayloadLobbyEndGameRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadLobbyEndGameRequestDefaultTypeInternal _PayloadLobbyEndGameRequest_default_instance_;
}  // namespace Proto
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_process_2flobby_2fend_5fgame_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_process_2flobby_2fend_5fgame_2eproto = nullptr;
const ::uint32_t
    TableStruct_process_2flobby_2fend_5fgame_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadLobbyEndGameRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadLobbyEndGameRequest, _impl_.user_id_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadLobbyEndGameResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadLobbyEndGameResponse, _impl_.success_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Proto::PayloadLobbyEndGameRequest)},
        {5, sizeof(::Proto::PayloadLobbyEndGameResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Proto::_PayloadLobbyEndGameRequest_default_instance_._instance,
    &::Proto::_PayloadLobbyEndGameResponse_default_instance_._instance,
};
const char descriptor_table_protodef_process_2flobby_2fend_5fgame_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\034process/lobby/end_game.proto\022\005Proto\032\024c"
    "ommon/session.proto\"-\n\032PayloadLobbyEndGa"
    "meRequest\022\017\n\007user_id\030\001 \001(\004\".\n\033PayloadLob"
    "byEndGameResponse\022\017\n\007success\030\001 \001(\010b\006prot"
    "o3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_process_2flobby_2fend_5fgame_2eproto_deps[1] = {
        &::descriptor_table_common_2fsession_2eproto,
};
static ::absl::once_flag descriptor_table_process_2flobby_2fend_5fgame_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_process_2flobby_2fend_5fgame_2eproto = {
    false,
    false,
    162,
    descriptor_table_protodef_process_2flobby_2fend_5fgame_2eproto,
    "process/lobby/end_game.proto",
    &descriptor_table_process_2flobby_2fend_5fgame_2eproto_once,
    descriptor_table_process_2flobby_2fend_5fgame_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_process_2flobby_2fend_5fgame_2eproto::offsets,
    file_level_enum_descriptors_process_2flobby_2fend_5fgame_2eproto,
    file_level_service_descriptors_process_2flobby_2fend_5fgame_2eproto,
};
namespace Proto {
// ===================================================================

class PayloadLobbyEndGameRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PayloadLobbyEndGameRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PayloadLobbyEndGameRequest, _impl_._has_bits_);
};

PayloadLobbyEndGameRequest::PayloadLobbyEndGameRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadLobbyEndGameRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.PayloadLobbyEndGameRequest)
}
PayloadLobbyEndGameRequest::PayloadLobbyEndGameRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadLobbyEndGameRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadLobbyEndGameRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PayloadLobbyEndGameRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PayloadLobbyEndGameRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.user_id_ = {};
}
PayloadLobbyEndGameRequest::~PayloadLobbyEndGameRequest() {
  // @@protoc_insertion_point(destructor:Proto.PayloadLobbyEndGameRequest)
  SharedDtor(*this);
}
inline void PayloadLobbyEndGameRequest::SharedDtor(MessageLite& self) {
  PayloadLobbyEndGameRequest& this_ = static_cast<PayloadLobbyEndGameRequest&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PayloadLobbyEndGameRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PayloadLobbyEndGameRequest(arena);
}
constexpr auto PayloadLobbyEndGameRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PayloadLobbyEndGameRequest),
                                            alignof(PayloadLobbyEndGameRequest));
}
constexpr auto PayloadLobbyEndGameRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PayloadLobbyEndGameRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PayloadLobbyEndGameRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PayloadLobbyEndGameRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PayloadLobbyEndGameRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PayloadLobbyEndGameRequest>(), &PayloadLobbyEndGameRequest::ByteSizeLong,
              &PayloadLobbyEndGameRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PayloadLobbyEndGameRequest, _impl_._cached_size_),
          false,
      },
      &PayloadLobbyEndGameRequest::kDescriptorMethods,
      &descriptor_table_process_2flobby_2fend_5fgame_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PayloadLobbyEndGameRequest_class_data_ =
        PayloadLobbyEndGameRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PayloadLobbyEndGameRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PayloadLobbyEndGameRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PayloadLobbyEndGameRequest_class_data_.tc_table);
  return PayloadLobbyEndGameRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
PayloadLobbyEndGameRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PayloadLobbyEndGameRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PayloadLobbyEndGameRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::PayloadLobbyEndGameRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 user_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PayloadLobbyEndGameRequest, _impl_.user_id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PayloadLobbyEndGameRequest, _impl_.user_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 user_id = 1;
    {PROTOBUF_FIELD_OFFSET(PayloadLobbyEndGameRequest, _impl_.user_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PayloadLobbyEndGameRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.PayloadLobbyEndGameRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PayloadLobbyEndGameRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PayloadLobbyEndGameRequest& this_ = static_cast<const PayloadLobbyEndGameRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PayloadLobbyEndGameRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PayloadLobbyEndGameRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.PayloadLobbyEndGameRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 user_id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_user_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_user_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.PayloadLobbyEndGameRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PayloadLobbyEndGameRequest::ByteSizeLong(const MessageLite& base) {
  const PayloadLobbyEndGameRequest& this_ = static_cast<const PayloadLobbyEndGameRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PayloadLobbyEndGameRequest::ByteSizeLong() const {
  const PayloadLobbyEndGameRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.PayloadLobbyEndGameRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // uint64 user_id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_user_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_user_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PayloadLobbyEndGameRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PayloadLobbyEndGameRequest*>(&to_msg);
  auto& from = static_cast<const PayloadLobbyEndGameRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.PayloadLobbyEndGameRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (from._internal_user_id() != 0) {
      _this->_impl_.user_id_ = from._impl_.user_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadLobbyEndGameRequest::CopyFrom(const PayloadLobbyEndGameRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.PayloadLobbyEndGameRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PayloadLobbyEndGameRequest::InternalSwap(PayloadLobbyEndGameRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.user_id_, other->_impl_.user_id_);
}

::google::protobuf::Metadata PayloadLobbyEndGameRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PayloadLobbyEndGameResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PayloadLobbyEndGameResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PayloadLobbyEndGameResponse, _impl_._has_bits_);
};

PayloadLobbyEndGameResponse::PayloadLobbyEndGameResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadLobbyEndGameResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.PayloadLobbyEndGameResponse)
}
PayloadLobbyEndGameResponse::PayloadLobbyEndGameResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadLobbyEndGameResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadLobbyEndGameResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PayloadLobbyEndGameResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PayloadLobbyEndGameResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
PayloadLobbyEndGameResponse::~PayloadLobbyEndGameResponse() {
  // @@protoc_insertion_point(destructor:Proto.PayloadLobbyEndGameResponse)
  SharedDtor(*this);
}
inline void PayloadLobbyEndGameResponse::SharedDtor(MessageLite& self) {
  PayloadLobbyEndGameResponse& this_ = static_cast<PayloadLobbyEndGameResponse&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PayloadLobbyEndGameResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PayloadLobbyEndGameResponse(arena);
}
constexpr auto PayloadLobbyEndGameResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PayloadLobbyEndGameResponse),
                                            alignof(PayloadLobbyEndGameResponse));
}
constexpr auto PayloadLobbyEndGameResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PayloadLobbyEndGameResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PayloadLobbyEndGameResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PayloadLobbyEndGameResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PayloadLobbyEndGameResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PayloadLobbyEndGameResponse>(), &PayloadLobbyEndGameResponse::ByteSizeLong,
              &PayloadLobbyEndGameResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PayloadLobbyEndGameResponse, _impl_._cached_size_),
          false,
      },
      &PayloadLobbyEndGameResponse::kDescriptorMethods,
      &descriptor_table_process_2flobby_2fend_5fgame_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PayloadLobbyEndGameResponse_class_data_ =
        PayloadLobbyEndGameResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PayloadLobbyEndGameResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PayloadLobbyEndGameResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PayloadLobbyEndGameResponse_class_data_.tc_table);
  return PayloadLobbyEndGameResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
PayloadLobbyEndGameResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PayloadLobbyEndGameResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PayloadLobbyEndGameResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::PayloadLobbyEndGameResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PayloadLobbyEndGameResponse, _impl_.success_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PayloadLobbyEndGameResponse, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(PayloadLobbyEndGameResponse, _impl_.success_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PayloadLobbyEndGameResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.PayloadLobbyEndGameResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.success_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PayloadLobbyEndGameResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PayloadLobbyEndGameResponse& this_ = static_cast<const PayloadLobbyEndGameResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PayloadLobbyEndGameResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PayloadLobbyEndGameResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.PayloadLobbyEndGameResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_success() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_success(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.PayloadLobbyEndGameResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PayloadLobbyEndGameResponse::ByteSizeLong(const MessageLite& base) {
  const PayloadLobbyEndGameResponse& this_ = static_cast<const PayloadLobbyEndGameResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PayloadLobbyEndGameResponse::ByteSizeLong() const {
  const PayloadLobbyEndGameResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.PayloadLobbyEndGameResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // bool success = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_success() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PayloadLobbyEndGameResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PayloadLobbyEndGameResponse*>(&to_msg);
  auto& from = static_cast<const PayloadLobbyEndGameResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.PayloadLobbyEndGameResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (from._internal_success() != 0) {
      _this->_impl_.success_ = from._impl_.success_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadLobbyEndGameResponse::CopyFrom(const PayloadLobbyEndGameResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.PayloadLobbyEndGameResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PayloadLobbyEndGameResponse::InternalSwap(PayloadLobbyEndGameResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata PayloadLobbyEndGameResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_process_2flobby_2fend_5fgame_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
