// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/gateway/packet.proto
// Protobuf C++ Version: 6.32.1

#include "process/gateway/packet.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Proto {

inline constexpr ToServerMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR ToServerMessage::ToServerMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ToServerMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ToServerMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ToServerMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ToServerMessageDefaultTypeInternal() {}
  union {
    ToServerMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ToServerMessageDefaultTypeInternal _ToServerMessage_default_instance_;

inline constexpr ToClientMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR ToClientMessage::ToClientMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ToClientMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ToClientMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ToClientMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ToClientMessageDefaultTypeInternal() {}
  union {
    ToClientMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ToClientMessageDefaultTypeInternal _ToClientMessage_default_instance_;
}  // namespace Proto
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_process_2fgateway_2fpacket_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_process_2fgateway_2fpacket_2eproto = nullptr;
const ::uint32_t
    TableStruct_process_2fgateway_2fpacket_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x004, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::ToServerMessage, _impl_._oneof_case_[0]),
        PROTOBUF_FIELD_OFFSET(::Proto::ToServerMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToServerMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToServerMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToServerMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToServerMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToServerMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToServerMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToServerMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToServerMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToServerMessage, _impl_.message_),
        0x004, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_._oneof_case_[0]),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Proto::ToServerMessage)},
        {12, sizeof(::Proto::ToClientMessage)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Proto::_ToServerMessage_default_instance_._instance,
    &::Proto::_ToClientMessage_default_instance_._instance,
};
const char descriptor_table_protodef_process_2fgateway_2fpacket_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\034process/gateway/packet.proto\022\005Proto\032\032p"
    "rocess/network/text.proto\032\033process/db/us"
    "er/login.proto\032\034process/db/user/logout.p"
    "roto\032\034process/db/user/signup.proto\032\027proc"
    "ess/zone/sync.proto\032\030process/zone/enemy."
    "proto\032%process/zone/client_data_getter.p"
    "roto\032 process/world/player_route.proto\032\036"
    "process/lobby/start_game.proto\032\034process/"
    "lobby/end_game.proto\032\031process/lobby/ente"
    "r.proto\032\030process/lobby/exit.proto\"\231\004\n\017To"
    "ServerMessage\0223\n\rlogin_request\030\001 \001(\0132\032.P"
    "roto.PayloadLoginRequestH\000\0225\n\016logout_req"
    "uest\030\002 \001(\0132\033.Proto.PayloadLogoutRequestH"
    "\000\0225\n\016signup_request\030\003 \001(\0132\033.Proto.Payloa"
    "dSignupRequestH\000\0229\n\nstart_game\030\004 \001(\0132#.P"
    "roto.PayloadLobbyStartGameRequestH\000\0225\n\010e"
    "nd_game\030\005 \001(\0132!.Proto.PayloadLobbyEndGam"
    "eRequestH\000\022K\n\032player_zone_enter_complete"
    "\030\006 \001(\0132%.Proto.PayloadPlayerZoneEnterCom"
    "pleteH\000\0225\n\016transform_sync\030\007 \001(\0132\033.Proto."
    "PayloadTransformSyncH\000\022/\n\013play_action\030\010 "
    "\001(\0132\030.Proto.PayloadPlayActionH\000\0221\n\014text_"
    "message\030\t \001(\0132\031.Proto.PayloadTextMessage"
    "H\000B\t\n\007message\"\344\006\n\017ToClientMessage\0227\n\017log"
    "out_response\030\002 \001(\0132\034.Proto.PayloadLogout"
    "ResponseH\000\0227\n\017signup_response\030\003 \001(\0132\034.Pr"
    "oto.PayloadSignupResponseH\000\022@\n\024lobby_ent"
    "er_response\030\004 \001(\0132 .Proto.PayloadLobbyEn"
    "terResponseH\000\022C\n\023start_game_response\030\005 \001"
    "(\0132$.Proto.PayloadLobbyStartGameResponse"
    "H\000\022\?\n\021end_game_response\030\006 \001(\0132\".Proto.Pa"
    "yloadLobbyEndGameResponseH\000\022F\n\027client_in"
    "itializer_data\030\007 \001(\0132#.Proto.PayloadClie"
    "ntInitializerDataH\000\0225\n\016transform_sync\030\010 "
    "\001(\0132\033.Proto.PayloadTransformSyncH\000\022/\n\013pl"
    "ay_action\030\t \001(\0132\030.Proto.PayloadPlayActio"
    "nH\000\0225\n\016entity_damaged\030\n \001(\0132\033.Proto.Payl"
    "oadEntityDamagedH\000\022/\n\013enemy_spawn\030\013 \001(\0132"
    "\030.Proto.PayloadEnemySpawnH\000\0223\n\renemy_des"
    "pawn\030\014 \001(\0132\032.Proto.PayloadEnemyDespawnH\000"
    "\022F\n\027zone_enter_notification\030\r \001(\0132#.Prot"
    "o.PayloadZoneEnterNotificationH\000\022D\n\026zone"
    "_exit_notification\030\016 \001(\0132\".Proto.Payload"
    "ZoneExitNotificationH\000\0221\n\014text_message\030\017"
    " \001(\0132\031.Proto.PayloadTextMessageH\000B\t\n\007mes"
    "sageb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_process_2fgateway_2fpacket_2eproto_deps[12] = {
        &::descriptor_table_process_2fdb_2fuser_2flogin_2eproto,
        &::descriptor_table_process_2fdb_2fuser_2flogout_2eproto,
        &::descriptor_table_process_2fdb_2fuser_2fsignup_2eproto,
        &::descriptor_table_process_2flobby_2fend_5fgame_2eproto,
        &::descriptor_table_process_2flobby_2fenter_2eproto,
        &::descriptor_table_process_2flobby_2fexit_2eproto,
        &::descriptor_table_process_2flobby_2fstart_5fgame_2eproto,
        &::descriptor_table_process_2fnetwork_2ftext_2eproto,
        &::descriptor_table_process_2fworld_2fplayer_5froute_2eproto,
        &::descriptor_table_process_2fzone_2fclient_5fdata_5fgetter_2eproto,
        &::descriptor_table_process_2fzone_2fenemy_2eproto,
        &::descriptor_table_process_2fzone_2fsync_2eproto,
};
static ::absl::once_flag descriptor_table_process_2fgateway_2fpacket_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_process_2fgateway_2fpacket_2eproto = {
    false,
    false,
    1812,
    descriptor_table_protodef_process_2fgateway_2fpacket_2eproto,
    "process/gateway/packet.proto",
    &descriptor_table_process_2fgateway_2fpacket_2eproto_once,
    descriptor_table_process_2fgateway_2fpacket_2eproto_deps,
    12,
    2,
    schemas,
    file_default_instances,
    TableStruct_process_2fgateway_2fpacket_2eproto::offsets,
    file_level_enum_descriptors_process_2fgateway_2fpacket_2eproto,
    file_level_service_descriptors_process_2fgateway_2fpacket_2eproto,
};
namespace Proto {
// ===================================================================

class ToServerMessage::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::Proto::ToServerMessage, _impl_._oneof_case_);
};

void ToServerMessage::set_allocated_login_request(::Proto::PayloadLoginRequest* PROTOBUF_NULLABLE login_request) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (login_request) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(login_request)->GetArena();
    if (message_arena != submessage_arena) {
      login_request = ::google::protobuf::internal::GetOwnedMessage(message_arena, login_request, submessage_arena);
    }
    set_has_login_request();
    _impl_.message_.login_request_ = login_request;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToServerMessage.login_request)
}
void ToServerMessage::clear_login_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kLoginRequest) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.login_request_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.login_request_);
    }
    clear_has_message();
  }
}
void ToServerMessage::set_allocated_logout_request(::Proto::PayloadLogoutRequest* PROTOBUF_NULLABLE logout_request) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (logout_request) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(logout_request)->GetArena();
    if (message_arena != submessage_arena) {
      logout_request = ::google::protobuf::internal::GetOwnedMessage(message_arena, logout_request, submessage_arena);
    }
    set_has_logout_request();
    _impl_.message_.logout_request_ = logout_request;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToServerMessage.logout_request)
}
void ToServerMessage::clear_logout_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kLogoutRequest) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.logout_request_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.logout_request_);
    }
    clear_has_message();
  }
}
void ToServerMessage::set_allocated_signup_request(::Proto::PayloadSignupRequest* PROTOBUF_NULLABLE signup_request) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (signup_request) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(signup_request)->GetArena();
    if (message_arena != submessage_arena) {
      signup_request = ::google::protobuf::internal::GetOwnedMessage(message_arena, signup_request, submessage_arena);
    }
    set_has_signup_request();
    _impl_.message_.signup_request_ = signup_request;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToServerMessage.signup_request)
}
void ToServerMessage::clear_signup_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kSignupRequest) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.signup_request_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.signup_request_);
    }
    clear_has_message();
  }
}
void ToServerMessage::set_allocated_start_game(::Proto::PayloadLobbyStartGameRequest* PROTOBUF_NULLABLE start_game) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (start_game) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(start_game)->GetArena();
    if (message_arena != submessage_arena) {
      start_game = ::google::protobuf::internal::GetOwnedMessage(message_arena, start_game, submessage_arena);
    }
    set_has_start_game();
    _impl_.message_.start_game_ = start_game;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToServerMessage.start_game)
}
void ToServerMessage::clear_start_game() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kStartGame) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.start_game_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.start_game_);
    }
    clear_has_message();
  }
}
void ToServerMessage::set_allocated_end_game(::Proto::PayloadLobbyEndGameRequest* PROTOBUF_NULLABLE end_game) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (end_game) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(end_game)->GetArena();
    if (message_arena != submessage_arena) {
      end_game = ::google::protobuf::internal::GetOwnedMessage(message_arena, end_game, submessage_arena);
    }
    set_has_end_game();
    _impl_.message_.end_game_ = end_game;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToServerMessage.end_game)
}
void ToServerMessage::clear_end_game() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kEndGame) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.end_game_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.end_game_);
    }
    clear_has_message();
  }
}
void ToServerMessage::set_allocated_player_zone_enter_complete(::Proto::PayloadPlayerZoneEnterComplete* PROTOBUF_NULLABLE player_zone_enter_complete) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (player_zone_enter_complete) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(player_zone_enter_complete)->GetArena();
    if (message_arena != submessage_arena) {
      player_zone_enter_complete = ::google::protobuf::internal::GetOwnedMessage(message_arena, player_zone_enter_complete, submessage_arena);
    }
    set_has_player_zone_enter_complete();
    _impl_.message_.player_zone_enter_complete_ = player_zone_enter_complete;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToServerMessage.player_zone_enter_complete)
}
void ToServerMessage::clear_player_zone_enter_complete() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kPlayerZoneEnterComplete) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.player_zone_enter_complete_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.player_zone_enter_complete_);
    }
    clear_has_message();
  }
}
void ToServerMessage::set_allocated_transform_sync(::Proto::PayloadTransformSync* PROTOBUF_NULLABLE transform_sync) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (transform_sync) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(transform_sync)->GetArena();
    if (message_arena != submessage_arena) {
      transform_sync = ::google::protobuf::internal::GetOwnedMessage(message_arena, transform_sync, submessage_arena);
    }
    set_has_transform_sync();
    _impl_.message_.transform_sync_ = transform_sync;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToServerMessage.transform_sync)
}
void ToServerMessage::clear_transform_sync() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kTransformSync) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.transform_sync_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.transform_sync_);
    }
    clear_has_message();
  }
}
void ToServerMessage::set_allocated_play_action(::Proto::PayloadPlayAction* PROTOBUF_NULLABLE play_action) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (play_action) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(play_action)->GetArena();
    if (message_arena != submessage_arena) {
      play_action = ::google::protobuf::internal::GetOwnedMessage(message_arena, play_action, submessage_arena);
    }
    set_has_play_action();
    _impl_.message_.play_action_ = play_action;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToServerMessage.play_action)
}
void ToServerMessage::clear_play_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kPlayAction) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.play_action_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.play_action_);
    }
    clear_has_message();
  }
}
void ToServerMessage::set_allocated_text_message(::Proto::PayloadTextMessage* PROTOBUF_NULLABLE text_message) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (text_message) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(text_message)->GetArena();
    if (message_arena != submessage_arena) {
      text_message = ::google::protobuf::internal::GetOwnedMessage(message_arena, text_message, submessage_arena);
    }
    set_has_text_message();
    _impl_.message_.text_message_ = text_message;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToServerMessage.text_message)
}
void ToServerMessage::clear_text_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kTextMessage) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.text_message_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.text_message_);
    }
    clear_has_message();
  }
}
ToServerMessage::ToServerMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ToServerMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.ToServerMessage)
}
PROTOBUF_NDEBUG_INLINE ToServerMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Proto::ToServerMessage& from_msg)
      : message_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

ToServerMessage::ToServerMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ToServerMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ToServerMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ToServerMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (message_case()) {
    case MESSAGE_NOT_SET:
      break;
      case kLoginRequest:
        _impl_.message_.login_request_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.login_request_);
        break;
      case kLogoutRequest:
        _impl_.message_.logout_request_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.logout_request_);
        break;
      case kSignupRequest:
        _impl_.message_.signup_request_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.signup_request_);
        break;
      case kStartGame:
        _impl_.message_.start_game_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.start_game_);
        break;
      case kEndGame:
        _impl_.message_.end_game_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.end_game_);
        break;
      case kPlayerZoneEnterComplete:
        _impl_.message_.player_zone_enter_complete_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.player_zone_enter_complete_);
        break;
      case kTransformSync:
        _impl_.message_.transform_sync_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.transform_sync_);
        break;
      case kPlayAction:
        _impl_.message_.play_action_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.play_action_);
        break;
      case kTextMessage:
        _impl_.message_.text_message_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.text_message_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Proto.ToServerMessage)
}
PROTOBUF_NDEBUG_INLINE ToServerMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : message_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void ToServerMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ToServerMessage::~ToServerMessage() {
  // @@protoc_insertion_point(destructor:Proto.ToServerMessage)
  SharedDtor(*this);
}
inline void ToServerMessage::SharedDtor(MessageLite& self) {
  ToServerMessage& this_ = static_cast<ToServerMessage&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_message()) {
    this_.clear_message();
  }
  this_._impl_.~Impl_();
}

void ToServerMessage::clear_message() {
// @@protoc_insertion_point(one_of_clear_start:Proto.ToServerMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (message_case()) {
    case kLoginRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.login_request_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.login_request_);
      }
      break;
    }
    case kLogoutRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.logout_request_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.logout_request_);
      }
      break;
    }
    case kSignupRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.signup_request_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.signup_request_);
      }
      break;
    }
    case kStartGame: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.start_game_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.start_game_);
      }
      break;
    }
    case kEndGame: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.end_game_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.end_game_);
      }
      break;
    }
    case kPlayerZoneEnterComplete: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.player_zone_enter_complete_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.player_zone_enter_complete_);
      }
      break;
    }
    case kTransformSync: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.transform_sync_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.transform_sync_);
      }
      break;
    }
    case kPlayAction: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.play_action_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.play_action_);
      }
      break;
    }
    case kTextMessage: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.text_message_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.text_message_);
      }
      break;
    }
    case MESSAGE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = MESSAGE_NOT_SET;
}


inline void* PROTOBUF_NONNULL ToServerMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ToServerMessage(arena);
}
constexpr auto ToServerMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ToServerMessage),
                                            alignof(ToServerMessage));
}
constexpr auto ToServerMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ToServerMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ToServerMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ToServerMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ToServerMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ToServerMessage>(), &ToServerMessage::ByteSizeLong,
              &ToServerMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ToServerMessage, _impl_._cached_size_),
          false,
      },
      &ToServerMessage::kDescriptorMethods,
      &descriptor_table_process_2fgateway_2fpacket_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ToServerMessage_class_data_ =
        ToServerMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ToServerMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ToServerMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ToServerMessage_class_data_.tc_table);
  return ToServerMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 9, 9, 0, 2>
ToServerMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    9, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    9,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ToServerMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::ToServerMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .Proto.PayloadLoginRequest login_request = 1;
    {PROTOBUF_FIELD_OFFSET(ToServerMessage, _impl_.message_.login_request_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadLogoutRequest logout_request = 2;
    {PROTOBUF_FIELD_OFFSET(ToServerMessage, _impl_.message_.logout_request_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadSignupRequest signup_request = 3;
    {PROTOBUF_FIELD_OFFSET(ToServerMessage, _impl_.message_.signup_request_), _Internal::kOneofCaseOffset + 0, 2, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadLobbyStartGameRequest start_game = 4;
    {PROTOBUF_FIELD_OFFSET(ToServerMessage, _impl_.message_.start_game_), _Internal::kOneofCaseOffset + 0, 3, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadLobbyEndGameRequest end_game = 5;
    {PROTOBUF_FIELD_OFFSET(ToServerMessage, _impl_.message_.end_game_), _Internal::kOneofCaseOffset + 0, 4, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadPlayerZoneEnterComplete player_zone_enter_complete = 6;
    {PROTOBUF_FIELD_OFFSET(ToServerMessage, _impl_.message_.player_zone_enter_complete_), _Internal::kOneofCaseOffset + 0, 5, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadTransformSync transform_sync = 7;
    {PROTOBUF_FIELD_OFFSET(ToServerMessage, _impl_.message_.transform_sync_), _Internal::kOneofCaseOffset + 0, 6, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadPlayAction play_action = 8;
    {PROTOBUF_FIELD_OFFSET(ToServerMessage, _impl_.message_.play_action_), _Internal::kOneofCaseOffset + 0, 7, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadTextMessage text_message = 9;
    {PROTOBUF_FIELD_OFFSET(ToServerMessage, _impl_.message_.text_message_), _Internal::kOneofCaseOffset + 0, 8, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Proto::PayloadLoginRequest>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadLogoutRequest>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadSignupRequest>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadLobbyStartGameRequest>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadLobbyEndGameRequest>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadPlayerZoneEnterComplete>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadTransformSync>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadPlayAction>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadTextMessage>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ToServerMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.ToServerMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_message();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ToServerMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ToServerMessage& this_ = static_cast<const ToServerMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ToServerMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ToServerMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.ToServerMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.message_case()) {
    case kLoginRequest: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, *this_._impl_.message_.login_request_, this_._impl_.message_.login_request_->GetCachedSize(), target,
          stream);
      break;
    }
    case kLogoutRequest: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *this_._impl_.message_.logout_request_, this_._impl_.message_.logout_request_->GetCachedSize(), target,
          stream);
      break;
    }
    case kSignupRequest: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *this_._impl_.message_.signup_request_, this_._impl_.message_.signup_request_->GetCachedSize(), target,
          stream);
      break;
    }
    case kStartGame: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *this_._impl_.message_.start_game_, this_._impl_.message_.start_game_->GetCachedSize(), target,
          stream);
      break;
    }
    case kEndGame: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          5, *this_._impl_.message_.end_game_, this_._impl_.message_.end_game_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPlayerZoneEnterComplete: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          6, *this_._impl_.message_.player_zone_enter_complete_, this_._impl_.message_.player_zone_enter_complete_->GetCachedSize(), target,
          stream);
      break;
    }
    case kTransformSync: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          7, *this_._impl_.message_.transform_sync_, this_._impl_.message_.transform_sync_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPlayAction: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          8, *this_._impl_.message_.play_action_, this_._impl_.message_.play_action_->GetCachedSize(), target,
          stream);
      break;
    }
    case kTextMessage: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          9, *this_._impl_.message_.text_message_, this_._impl_.message_.text_message_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.ToServerMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ToServerMessage::ByteSizeLong(const MessageLite& base) {
  const ToServerMessage& this_ = static_cast<const ToServerMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ToServerMessage::ByteSizeLong() const {
  const ToServerMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.ToServerMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.message_case()) {
    // .Proto.PayloadLoginRequest login_request = 1;
    case kLoginRequest: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.login_request_);
      break;
    }
    // .Proto.PayloadLogoutRequest logout_request = 2;
    case kLogoutRequest: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.logout_request_);
      break;
    }
    // .Proto.PayloadSignupRequest signup_request = 3;
    case kSignupRequest: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.signup_request_);
      break;
    }
    // .Proto.PayloadLobbyStartGameRequest start_game = 4;
    case kStartGame: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.start_game_);
      break;
    }
    // .Proto.PayloadLobbyEndGameRequest end_game = 5;
    case kEndGame: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.end_game_);
      break;
    }
    // .Proto.PayloadPlayerZoneEnterComplete player_zone_enter_complete = 6;
    case kPlayerZoneEnterComplete: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.player_zone_enter_complete_);
      break;
    }
    // .Proto.PayloadTransformSync transform_sync = 7;
    case kTransformSync: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.transform_sync_);
      break;
    }
    // .Proto.PayloadPlayAction play_action = 8;
    case kPlayAction: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.play_action_);
      break;
    }
    // .Proto.PayloadTextMessage text_message = 9;
    case kTextMessage: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.text_message_);
      break;
    }
    case MESSAGE_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ToServerMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ToServerMessage*>(&to_msg);
  auto& from = static_cast<const ToServerMessage&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.ToServerMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_message();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kLoginRequest: {
        if (oneof_needs_init) {
          _this->_impl_.message_.login_request_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.login_request_);
        } else {
          _this->_impl_.message_.login_request_->MergeFrom(*from._impl_.message_.login_request_);
        }
        break;
      }
      case kLogoutRequest: {
        if (oneof_needs_init) {
          _this->_impl_.message_.logout_request_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.logout_request_);
        } else {
          _this->_impl_.message_.logout_request_->MergeFrom(*from._impl_.message_.logout_request_);
        }
        break;
      }
      case kSignupRequest: {
        if (oneof_needs_init) {
          _this->_impl_.message_.signup_request_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.signup_request_);
        } else {
          _this->_impl_.message_.signup_request_->MergeFrom(*from._impl_.message_.signup_request_);
        }
        break;
      }
      case kStartGame: {
        if (oneof_needs_init) {
          _this->_impl_.message_.start_game_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.start_game_);
        } else {
          _this->_impl_.message_.start_game_->MergeFrom(*from._impl_.message_.start_game_);
        }
        break;
      }
      case kEndGame: {
        if (oneof_needs_init) {
          _this->_impl_.message_.end_game_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.end_game_);
        } else {
          _this->_impl_.message_.end_game_->MergeFrom(*from._impl_.message_.end_game_);
        }
        break;
      }
      case kPlayerZoneEnterComplete: {
        if (oneof_needs_init) {
          _this->_impl_.message_.player_zone_enter_complete_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.player_zone_enter_complete_);
        } else {
          _this->_impl_.message_.player_zone_enter_complete_->MergeFrom(*from._impl_.message_.player_zone_enter_complete_);
        }
        break;
      }
      case kTransformSync: {
        if (oneof_needs_init) {
          _this->_impl_.message_.transform_sync_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.transform_sync_);
        } else {
          _this->_impl_.message_.transform_sync_->MergeFrom(*from._impl_.message_.transform_sync_);
        }
        break;
      }
      case kPlayAction: {
        if (oneof_needs_init) {
          _this->_impl_.message_.play_action_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.play_action_);
        } else {
          _this->_impl_.message_.play_action_->MergeFrom(*from._impl_.message_.play_action_);
        }
        break;
      }
      case kTextMessage: {
        if (oneof_needs_init) {
          _this->_impl_.message_.text_message_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.text_message_);
        } else {
          _this->_impl_.message_.text_message_->MergeFrom(*from._impl_.message_.text_message_);
        }
        break;
      }
      case MESSAGE_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ToServerMessage::CopyFrom(const ToServerMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.ToServerMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ToServerMessage::InternalSwap(ToServerMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.message_, other->_impl_.message_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata ToServerMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ToClientMessage::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::Proto::ToClientMessage, _impl_._oneof_case_);
};

void ToClientMessage::set_allocated_logout_response(::Proto::PayloadLogoutResponse* PROTOBUF_NULLABLE logout_response) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (logout_response) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(logout_response)->GetArena();
    if (message_arena != submessage_arena) {
      logout_response = ::google::protobuf::internal::GetOwnedMessage(message_arena, logout_response, submessage_arena);
    }
    set_has_logout_response();
    _impl_.message_.logout_response_ = logout_response;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.logout_response)
}
void ToClientMessage::clear_logout_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kLogoutResponse) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.logout_response_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.logout_response_);
    }
    clear_has_message();
  }
}
void ToClientMessage::set_allocated_signup_response(::Proto::PayloadSignupResponse* PROTOBUF_NULLABLE signup_response) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (signup_response) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(signup_response)->GetArena();
    if (message_arena != submessage_arena) {
      signup_response = ::google::protobuf::internal::GetOwnedMessage(message_arena, signup_response, submessage_arena);
    }
    set_has_signup_response();
    _impl_.message_.signup_response_ = signup_response;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.signup_response)
}
void ToClientMessage::clear_signup_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kSignupResponse) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.signup_response_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.signup_response_);
    }
    clear_has_message();
  }
}
void ToClientMessage::set_allocated_lobby_enter_response(::Proto::PayloadLobbyEnterResponse* PROTOBUF_NULLABLE lobby_enter_response) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (lobby_enter_response) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(lobby_enter_response)->GetArena();
    if (message_arena != submessage_arena) {
      lobby_enter_response = ::google::protobuf::internal::GetOwnedMessage(message_arena, lobby_enter_response, submessage_arena);
    }
    set_has_lobby_enter_response();
    _impl_.message_.lobby_enter_response_ = lobby_enter_response;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.lobby_enter_response)
}
void ToClientMessage::clear_lobby_enter_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kLobbyEnterResponse) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.lobby_enter_response_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.lobby_enter_response_);
    }
    clear_has_message();
  }
}
void ToClientMessage::set_allocated_start_game_response(::Proto::PayloadLobbyStartGameResponse* PROTOBUF_NULLABLE start_game_response) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (start_game_response) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(start_game_response)->GetArena();
    if (message_arena != submessage_arena) {
      start_game_response = ::google::protobuf::internal::GetOwnedMessage(message_arena, start_game_response, submessage_arena);
    }
    set_has_start_game_response();
    _impl_.message_.start_game_response_ = start_game_response;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.start_game_response)
}
void ToClientMessage::clear_start_game_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kStartGameResponse) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.start_game_response_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.start_game_response_);
    }
    clear_has_message();
  }
}
void ToClientMessage::set_allocated_end_game_response(::Proto::PayloadLobbyEndGameResponse* PROTOBUF_NULLABLE end_game_response) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (end_game_response) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(end_game_response)->GetArena();
    if (message_arena != submessage_arena) {
      end_game_response = ::google::protobuf::internal::GetOwnedMessage(message_arena, end_game_response, submessage_arena);
    }
    set_has_end_game_response();
    _impl_.message_.end_game_response_ = end_game_response;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.end_game_response)
}
void ToClientMessage::clear_end_game_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kEndGameResponse) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.end_game_response_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.end_game_response_);
    }
    clear_has_message();
  }
}
void ToClientMessage::set_allocated_client_initializer_data(::Proto::PayloadClientInitializerData* PROTOBUF_NULLABLE client_initializer_data) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (client_initializer_data) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(client_initializer_data)->GetArena();
    if (message_arena != submessage_arena) {
      client_initializer_data = ::google::protobuf::internal::GetOwnedMessage(message_arena, client_initializer_data, submessage_arena);
    }
    set_has_client_initializer_data();
    _impl_.message_.client_initializer_data_ = client_initializer_data;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.client_initializer_data)
}
void ToClientMessage::clear_client_initializer_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kClientInitializerData) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.client_initializer_data_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.client_initializer_data_);
    }
    clear_has_message();
  }
}
void ToClientMessage::set_allocated_transform_sync(::Proto::PayloadTransformSync* PROTOBUF_NULLABLE transform_sync) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (transform_sync) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(transform_sync)->GetArena();
    if (message_arena != submessage_arena) {
      transform_sync = ::google::protobuf::internal::GetOwnedMessage(message_arena, transform_sync, submessage_arena);
    }
    set_has_transform_sync();
    _impl_.message_.transform_sync_ = transform_sync;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.transform_sync)
}
void ToClientMessage::clear_transform_sync() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kTransformSync) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.transform_sync_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.transform_sync_);
    }
    clear_has_message();
  }
}
void ToClientMessage::set_allocated_play_action(::Proto::PayloadPlayAction* PROTOBUF_NULLABLE play_action) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (play_action) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(play_action)->GetArena();
    if (message_arena != submessage_arena) {
      play_action = ::google::protobuf::internal::GetOwnedMessage(message_arena, play_action, submessage_arena);
    }
    set_has_play_action();
    _impl_.message_.play_action_ = play_action;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.play_action)
}
void ToClientMessage::clear_play_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kPlayAction) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.play_action_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.play_action_);
    }
    clear_has_message();
  }
}
void ToClientMessage::set_allocated_entity_damaged(::Proto::PayloadEntityDamaged* PROTOBUF_NULLABLE entity_damaged) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (entity_damaged) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(entity_damaged)->GetArena();
    if (message_arena != submessage_arena) {
      entity_damaged = ::google::protobuf::internal::GetOwnedMessage(message_arena, entity_damaged, submessage_arena);
    }
    set_has_entity_damaged();
    _impl_.message_.entity_damaged_ = entity_damaged;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.entity_damaged)
}
void ToClientMessage::clear_entity_damaged() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kEntityDamaged) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.entity_damaged_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.entity_damaged_);
    }
    clear_has_message();
  }
}
void ToClientMessage::set_allocated_enemy_spawn(::Proto::PayloadEnemySpawn* PROTOBUF_NULLABLE enemy_spawn) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (enemy_spawn) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(enemy_spawn)->GetArena();
    if (message_arena != submessage_arena) {
      enemy_spawn = ::google::protobuf::internal::GetOwnedMessage(message_arena, enemy_spawn, submessage_arena);
    }
    set_has_enemy_spawn();
    _impl_.message_.enemy_spawn_ = enemy_spawn;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.enemy_spawn)
}
void ToClientMessage::clear_enemy_spawn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kEnemySpawn) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.enemy_spawn_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.enemy_spawn_);
    }
    clear_has_message();
  }
}
void ToClientMessage::set_allocated_enemy_despawn(::Proto::PayloadEnemyDespawn* PROTOBUF_NULLABLE enemy_despawn) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (enemy_despawn) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(enemy_despawn)->GetArena();
    if (message_arena != submessage_arena) {
      enemy_despawn = ::google::protobuf::internal::GetOwnedMessage(message_arena, enemy_despawn, submessage_arena);
    }
    set_has_enemy_despawn();
    _impl_.message_.enemy_despawn_ = enemy_despawn;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.enemy_despawn)
}
void ToClientMessage::clear_enemy_despawn() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kEnemyDespawn) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.enemy_despawn_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.enemy_despawn_);
    }
    clear_has_message();
  }
}
void ToClientMessage::set_allocated_zone_enter_notification(::Proto::PayloadZoneEnterNotification* PROTOBUF_NULLABLE zone_enter_notification) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (zone_enter_notification) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(zone_enter_notification)->GetArena();
    if (message_arena != submessage_arena) {
      zone_enter_notification = ::google::protobuf::internal::GetOwnedMessage(message_arena, zone_enter_notification, submessage_arena);
    }
    set_has_zone_enter_notification();
    _impl_.message_.zone_enter_notification_ = zone_enter_notification;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.zone_enter_notification)
}
void ToClientMessage::clear_zone_enter_notification() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kZoneEnterNotification) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.zone_enter_notification_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.zone_enter_notification_);
    }
    clear_has_message();
  }
}
void ToClientMessage::set_allocated_zone_exit_notification(::Proto::PayloadZoneExitNotification* PROTOBUF_NULLABLE zone_exit_notification) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (zone_exit_notification) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(zone_exit_notification)->GetArena();
    if (message_arena != submessage_arena) {
      zone_exit_notification = ::google::protobuf::internal::GetOwnedMessage(message_arena, zone_exit_notification, submessage_arena);
    }
    set_has_zone_exit_notification();
    _impl_.message_.zone_exit_notification_ = zone_exit_notification;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.zone_exit_notification)
}
void ToClientMessage::clear_zone_exit_notification() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kZoneExitNotification) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.zone_exit_notification_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.zone_exit_notification_);
    }
    clear_has_message();
  }
}
void ToClientMessage::set_allocated_text_message(::Proto::PayloadTextMessage* PROTOBUF_NULLABLE text_message) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_message();
  if (text_message) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(text_message)->GetArena();
    if (message_arena != submessage_arena) {
      text_message = ::google::protobuf::internal::GetOwnedMessage(message_arena, text_message, submessage_arena);
    }
    set_has_text_message();
    _impl_.message_.text_message_ = text_message;
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.ToClientMessage.text_message)
}
void ToClientMessage::clear_text_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kTextMessage) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.text_message_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.text_message_);
    }
    clear_has_message();
  }
}
ToClientMessage::ToClientMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ToClientMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.ToClientMessage)
}
PROTOBUF_NDEBUG_INLINE ToClientMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Proto::ToClientMessage& from_msg)
      : message_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

ToClientMessage::ToClientMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ToClientMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ToClientMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ToClientMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (message_case()) {
    case MESSAGE_NOT_SET:
      break;
      case kLogoutResponse:
        _impl_.message_.logout_response_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.logout_response_);
        break;
      case kSignupResponse:
        _impl_.message_.signup_response_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.signup_response_);
        break;
      case kLobbyEnterResponse:
        _impl_.message_.lobby_enter_response_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.lobby_enter_response_);
        break;
      case kStartGameResponse:
        _impl_.message_.start_game_response_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.start_game_response_);
        break;
      case kEndGameResponse:
        _impl_.message_.end_game_response_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.end_game_response_);
        break;
      case kClientInitializerData:
        _impl_.message_.client_initializer_data_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.client_initializer_data_);
        break;
      case kTransformSync:
        _impl_.message_.transform_sync_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.transform_sync_);
        break;
      case kPlayAction:
        _impl_.message_.play_action_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.play_action_);
        break;
      case kEntityDamaged:
        _impl_.message_.entity_damaged_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.entity_damaged_);
        break;
      case kEnemySpawn:
        _impl_.message_.enemy_spawn_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.enemy_spawn_);
        break;
      case kEnemyDespawn:
        _impl_.message_.enemy_despawn_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.enemy_despawn_);
        break;
      case kZoneEnterNotification:
        _impl_.message_.zone_enter_notification_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.zone_enter_notification_);
        break;
      case kZoneExitNotification:
        _impl_.message_.zone_exit_notification_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.zone_exit_notification_);
        break;
      case kTextMessage:
        _impl_.message_.text_message_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.text_message_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Proto.ToClientMessage)
}
PROTOBUF_NDEBUG_INLINE ToClientMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : message_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void ToClientMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ToClientMessage::~ToClientMessage() {
  // @@protoc_insertion_point(destructor:Proto.ToClientMessage)
  SharedDtor(*this);
}
inline void ToClientMessage::SharedDtor(MessageLite& self) {
  ToClientMessage& this_ = static_cast<ToClientMessage&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_message()) {
    this_.clear_message();
  }
  this_._impl_.~Impl_();
}

void ToClientMessage::clear_message() {
// @@protoc_insertion_point(one_of_clear_start:Proto.ToClientMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (message_case()) {
    case kLogoutResponse: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.logout_response_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.logout_response_);
      }
      break;
    }
    case kSignupResponse: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.signup_response_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.signup_response_);
      }
      break;
    }
    case kLobbyEnterResponse: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.lobby_enter_response_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.lobby_enter_response_);
      }
      break;
    }
    case kStartGameResponse: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.start_game_response_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.start_game_response_);
      }
      break;
    }
    case kEndGameResponse: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.end_game_response_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.end_game_response_);
      }
      break;
    }
    case kClientInitializerData: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.client_initializer_data_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.client_initializer_data_);
      }
      break;
    }
    case kTransformSync: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.transform_sync_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.transform_sync_);
      }
      break;
    }
    case kPlayAction: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.play_action_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.play_action_);
      }
      break;
    }
    case kEntityDamaged: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.entity_damaged_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.entity_damaged_);
      }
      break;
    }
    case kEnemySpawn: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.enemy_spawn_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.enemy_spawn_);
      }
      break;
    }
    case kEnemyDespawn: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.enemy_despawn_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.enemy_despawn_);
      }
      break;
    }
    case kZoneEnterNotification: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.zone_enter_notification_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.zone_enter_notification_);
      }
      break;
    }
    case kZoneExitNotification: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.zone_exit_notification_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.zone_exit_notification_);
      }
      break;
    }
    case kTextMessage: {
      if (GetArena() == nullptr) {
        delete _impl_.message_.text_message_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.text_message_);
      }
      break;
    }
    case MESSAGE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = MESSAGE_NOT_SET;
}


inline void* PROTOBUF_NONNULL ToClientMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ToClientMessage(arena);
}
constexpr auto ToClientMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ToClientMessage),
                                            alignof(ToClientMessage));
}
constexpr auto ToClientMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ToClientMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ToClientMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ToClientMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ToClientMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ToClientMessage>(), &ToClientMessage::ByteSizeLong,
              &ToClientMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_._cached_size_),
          false,
      },
      &ToClientMessage::kDescriptorMethods,
      &descriptor_table_process_2fgateway_2fpacket_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ToClientMessage_class_data_ =
        ToClientMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ToClientMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ToClientMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ToClientMessage_class_data_.tc_table);
  return ToClientMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 14, 14, 0, 2>
ToClientMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    15, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294934529,  // skipmap
    offsetof(decltype(_table_), field_entries),
    14,  // num_field_entries
    14,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ToClientMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::ToClientMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .Proto.PayloadLogoutResponse logout_response = 2;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.logout_response_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadSignupResponse signup_response = 3;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.signup_response_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadLobbyEnterResponse lobby_enter_response = 4;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.lobby_enter_response_), _Internal::kOneofCaseOffset + 0, 2, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadLobbyStartGameResponse start_game_response = 5;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.start_game_response_), _Internal::kOneofCaseOffset + 0, 3, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadLobbyEndGameResponse end_game_response = 6;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.end_game_response_), _Internal::kOneofCaseOffset + 0, 4, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadClientInitializerData client_initializer_data = 7;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.client_initializer_data_), _Internal::kOneofCaseOffset + 0, 5, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadTransformSync transform_sync = 8;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.transform_sync_), _Internal::kOneofCaseOffset + 0, 6, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadPlayAction play_action = 9;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.play_action_), _Internal::kOneofCaseOffset + 0, 7, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadEntityDamaged entity_damaged = 10;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.entity_damaged_), _Internal::kOneofCaseOffset + 0, 8, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadEnemySpawn enemy_spawn = 11;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.enemy_spawn_), _Internal::kOneofCaseOffset + 0, 9, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadEnemyDespawn enemy_despawn = 12;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.enemy_despawn_), _Internal::kOneofCaseOffset + 0, 10, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadZoneEnterNotification zone_enter_notification = 13;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.zone_enter_notification_), _Internal::kOneofCaseOffset + 0, 11, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadZoneExitNotification zone_exit_notification = 14;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.zone_exit_notification_), _Internal::kOneofCaseOffset + 0, 12, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Proto.PayloadTextMessage text_message = 15;
    {PROTOBUF_FIELD_OFFSET(ToClientMessage, _impl_.message_.text_message_), _Internal::kOneofCaseOffset + 0, 13, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Proto::PayloadLogoutResponse>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadSignupResponse>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadLobbyEnterResponse>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadLobbyStartGameResponse>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadLobbyEndGameResponse>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadClientInitializerData>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadTransformSync>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadPlayAction>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadEntityDamaged>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadEnemySpawn>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadEnemyDespawn>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadZoneEnterNotification>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadZoneExitNotification>()},
      {::_pbi::TcParser::GetTable<::Proto::PayloadTextMessage>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ToClientMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.ToClientMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_message();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ToClientMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ToClientMessage& this_ = static_cast<const ToClientMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ToClientMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ToClientMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.ToClientMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.message_case()) {
    case kLogoutResponse: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *this_._impl_.message_.logout_response_, this_._impl_.message_.logout_response_->GetCachedSize(), target,
          stream);
      break;
    }
    case kSignupResponse: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *this_._impl_.message_.signup_response_, this_._impl_.message_.signup_response_->GetCachedSize(), target,
          stream);
      break;
    }
    case kLobbyEnterResponse: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *this_._impl_.message_.lobby_enter_response_, this_._impl_.message_.lobby_enter_response_->GetCachedSize(), target,
          stream);
      break;
    }
    case kStartGameResponse: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          5, *this_._impl_.message_.start_game_response_, this_._impl_.message_.start_game_response_->GetCachedSize(), target,
          stream);
      break;
    }
    case kEndGameResponse: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          6, *this_._impl_.message_.end_game_response_, this_._impl_.message_.end_game_response_->GetCachedSize(), target,
          stream);
      break;
    }
    case kClientInitializerData: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          7, *this_._impl_.message_.client_initializer_data_, this_._impl_.message_.client_initializer_data_->GetCachedSize(), target,
          stream);
      break;
    }
    case kTransformSync: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          8, *this_._impl_.message_.transform_sync_, this_._impl_.message_.transform_sync_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPlayAction: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          9, *this_._impl_.message_.play_action_, this_._impl_.message_.play_action_->GetCachedSize(), target,
          stream);
      break;
    }
    case kEntityDamaged: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          10, *this_._impl_.message_.entity_damaged_, this_._impl_.message_.entity_damaged_->GetCachedSize(), target,
          stream);
      break;
    }
    case kEnemySpawn: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          11, *this_._impl_.message_.enemy_spawn_, this_._impl_.message_.enemy_spawn_->GetCachedSize(), target,
          stream);
      break;
    }
    case kEnemyDespawn: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          12, *this_._impl_.message_.enemy_despawn_, this_._impl_.message_.enemy_despawn_->GetCachedSize(), target,
          stream);
      break;
    }
    case kZoneEnterNotification: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          13, *this_._impl_.message_.zone_enter_notification_, this_._impl_.message_.zone_enter_notification_->GetCachedSize(), target,
          stream);
      break;
    }
    case kZoneExitNotification: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          14, *this_._impl_.message_.zone_exit_notification_, this_._impl_.message_.zone_exit_notification_->GetCachedSize(), target,
          stream);
      break;
    }
    case kTextMessage: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          15, *this_._impl_.message_.text_message_, this_._impl_.message_.text_message_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.ToClientMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ToClientMessage::ByteSizeLong(const MessageLite& base) {
  const ToClientMessage& this_ = static_cast<const ToClientMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ToClientMessage::ByteSizeLong() const {
  const ToClientMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.ToClientMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.message_case()) {
    // .Proto.PayloadLogoutResponse logout_response = 2;
    case kLogoutResponse: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.logout_response_);
      break;
    }
    // .Proto.PayloadSignupResponse signup_response = 3;
    case kSignupResponse: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.signup_response_);
      break;
    }
    // .Proto.PayloadLobbyEnterResponse lobby_enter_response = 4;
    case kLobbyEnterResponse: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.lobby_enter_response_);
      break;
    }
    // .Proto.PayloadLobbyStartGameResponse start_game_response = 5;
    case kStartGameResponse: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.start_game_response_);
      break;
    }
    // .Proto.PayloadLobbyEndGameResponse end_game_response = 6;
    case kEndGameResponse: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.end_game_response_);
      break;
    }
    // .Proto.PayloadClientInitializerData client_initializer_data = 7;
    case kClientInitializerData: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.client_initializer_data_);
      break;
    }
    // .Proto.PayloadTransformSync transform_sync = 8;
    case kTransformSync: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.transform_sync_);
      break;
    }
    // .Proto.PayloadPlayAction play_action = 9;
    case kPlayAction: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.play_action_);
      break;
    }
    // .Proto.PayloadEntityDamaged entity_damaged = 10;
    case kEntityDamaged: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.entity_damaged_);
      break;
    }
    // .Proto.PayloadEnemySpawn enemy_spawn = 11;
    case kEnemySpawn: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.enemy_spawn_);
      break;
    }
    // .Proto.PayloadEnemyDespawn enemy_despawn = 12;
    case kEnemyDespawn: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.enemy_despawn_);
      break;
    }
    // .Proto.PayloadZoneEnterNotification zone_enter_notification = 13;
    case kZoneEnterNotification: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.zone_enter_notification_);
      break;
    }
    // .Proto.PayloadZoneExitNotification zone_exit_notification = 14;
    case kZoneExitNotification: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.zone_exit_notification_);
      break;
    }
    // .Proto.PayloadTextMessage text_message = 15;
    case kTextMessage: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.message_.text_message_);
      break;
    }
    case MESSAGE_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ToClientMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ToClientMessage*>(&to_msg);
  auto& from = static_cast<const ToClientMessage&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.ToClientMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_message();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kLogoutResponse: {
        if (oneof_needs_init) {
          _this->_impl_.message_.logout_response_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.logout_response_);
        } else {
          _this->_impl_.message_.logout_response_->MergeFrom(*from._impl_.message_.logout_response_);
        }
        break;
      }
      case kSignupResponse: {
        if (oneof_needs_init) {
          _this->_impl_.message_.signup_response_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.signup_response_);
        } else {
          _this->_impl_.message_.signup_response_->MergeFrom(*from._impl_.message_.signup_response_);
        }
        break;
      }
      case kLobbyEnterResponse: {
        if (oneof_needs_init) {
          _this->_impl_.message_.lobby_enter_response_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.lobby_enter_response_);
        } else {
          _this->_impl_.message_.lobby_enter_response_->MergeFrom(*from._impl_.message_.lobby_enter_response_);
        }
        break;
      }
      case kStartGameResponse: {
        if (oneof_needs_init) {
          _this->_impl_.message_.start_game_response_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.start_game_response_);
        } else {
          _this->_impl_.message_.start_game_response_->MergeFrom(*from._impl_.message_.start_game_response_);
        }
        break;
      }
      case kEndGameResponse: {
        if (oneof_needs_init) {
          _this->_impl_.message_.end_game_response_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.end_game_response_);
        } else {
          _this->_impl_.message_.end_game_response_->MergeFrom(*from._impl_.message_.end_game_response_);
        }
        break;
      }
      case kClientInitializerData: {
        if (oneof_needs_init) {
          _this->_impl_.message_.client_initializer_data_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.client_initializer_data_);
        } else {
          _this->_impl_.message_.client_initializer_data_->MergeFrom(*from._impl_.message_.client_initializer_data_);
        }
        break;
      }
      case kTransformSync: {
        if (oneof_needs_init) {
          _this->_impl_.message_.transform_sync_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.transform_sync_);
        } else {
          _this->_impl_.message_.transform_sync_->MergeFrom(*from._impl_.message_.transform_sync_);
        }
        break;
      }
      case kPlayAction: {
        if (oneof_needs_init) {
          _this->_impl_.message_.play_action_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.play_action_);
        } else {
          _this->_impl_.message_.play_action_->MergeFrom(*from._impl_.message_.play_action_);
        }
        break;
      }
      case kEntityDamaged: {
        if (oneof_needs_init) {
          _this->_impl_.message_.entity_damaged_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.entity_damaged_);
        } else {
          _this->_impl_.message_.entity_damaged_->MergeFrom(*from._impl_.message_.entity_damaged_);
        }
        break;
      }
      case kEnemySpawn: {
        if (oneof_needs_init) {
          _this->_impl_.message_.enemy_spawn_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.enemy_spawn_);
        } else {
          _this->_impl_.message_.enemy_spawn_->MergeFrom(*from._impl_.message_.enemy_spawn_);
        }
        break;
      }
      case kEnemyDespawn: {
        if (oneof_needs_init) {
          _this->_impl_.message_.enemy_despawn_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.enemy_despawn_);
        } else {
          _this->_impl_.message_.enemy_despawn_->MergeFrom(*from._impl_.message_.enemy_despawn_);
        }
        break;
      }
      case kZoneEnterNotification: {
        if (oneof_needs_init) {
          _this->_impl_.message_.zone_enter_notification_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.zone_enter_notification_);
        } else {
          _this->_impl_.message_.zone_enter_notification_->MergeFrom(*from._impl_.message_.zone_enter_notification_);
        }
        break;
      }
      case kZoneExitNotification: {
        if (oneof_needs_init) {
          _this->_impl_.message_.zone_exit_notification_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.zone_exit_notification_);
        } else {
          _this->_impl_.message_.zone_exit_notification_->MergeFrom(*from._impl_.message_.zone_exit_notification_);
        }
        break;
      }
      case kTextMessage: {
        if (oneof_needs_init) {
          _this->_impl_.message_.text_message_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.message_.text_message_);
        } else {
          _this->_impl_.message_.text_message_->MergeFrom(*from._impl_.message_.text_message_);
        }
        break;
      }
      case MESSAGE_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ToClientMessage::CopyFrom(const ToClientMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.ToClientMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ToClientMessage::InternalSwap(ToClientMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.message_, other->_impl_.message_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata ToClientMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_process_2fgateway_2fpacket_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
