// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/zone/sync.proto
// Protobuf C++ Version: 6.32.1

#include "process/zone/sync.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Proto {

inline constexpr PayloadZoneExitNotification::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR PayloadZoneExitNotification::PayloadZoneExitNotification(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PayloadZoneExitNotification_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PayloadZoneExitNotificationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadZoneExitNotificationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadZoneExitNotificationDefaultTypeInternal() {}
  union {
    PayloadZoneExitNotification _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadZoneExitNotificationDefaultTypeInternal _PayloadZoneExitNotification_default_instance_;

inline constexpr PayloadPlayAction::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_{::uint64_t{0u}},
        target_id_{::uint64_t{0u}},
        timestamp_{::int64_t{0}},
        action_id_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR PayloadPlayAction::PayloadPlayAction(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PayloadPlayAction_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PayloadPlayActionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadPlayActionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadPlayActionDefaultTypeInternal() {}
  union {
    PayloadPlayAction _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadPlayActionDefaultTypeInternal _PayloadPlayAction_default_instance_;

inline constexpr PayloadEntityDamaged::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        entity_id_{::uint64_t{0u}},
        damage_{0},
        current_hp_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PayloadEntityDamaged::PayloadEntityDamaged(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PayloadEntityDamaged_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PayloadEntityDamagedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadEntityDamagedDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadEntityDamagedDefaultTypeInternal() {}
  union {
    PayloadEntityDamaged _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadEntityDamagedDefaultTypeInternal _PayloadEntityDamaged_default_instance_;

inline constexpr PayloadZoneEnterNotification::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        username_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        position_{nullptr},
        id_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR PayloadZoneEnterNotification::PayloadZoneEnterNotification(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PayloadZoneEnterNotification_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PayloadZoneEnterNotificationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadZoneEnterNotificationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadZoneEnterNotificationDefaultTypeInternal() {}
  union {
    PayloadZoneEnterNotification _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadZoneEnterNotificationDefaultTypeInternal _PayloadZoneEnterNotification_default_instance_;

inline constexpr PayloadTransformSync::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        position_{nullptr},
        id_{::uint64_t{0u}},
        timestamp_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR PayloadTransformSync::PayloadTransformSync(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PayloadTransformSync_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PayloadTransformSyncDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadTransformSyncDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadTransformSyncDefaultTypeInternal() {}
  union {
    PayloadTransformSync _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadTransformSyncDefaultTypeInternal _PayloadTransformSync_default_instance_;
}  // namespace Proto
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_process_2fzone_2fsync_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_process_2fzone_2fsync_2eproto = nullptr;
const ::uint32_t
    TableStruct_process_2fzone_2fsync_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadTransformSync, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadTransformSync, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadTransformSync, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadTransformSync, _impl_.position_),
        1,
        2,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadPlayAction, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadPlayAction, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadPlayAction, _impl_.target_id_),
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadPlayAction, _impl_.action_id_),
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadPlayAction, _impl_.timestamp_),
        0,
        1,
        3,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadEntityDamaged, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadEntityDamaged, _impl_.entity_id_),
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadEntityDamaged, _impl_.damage_),
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadEntityDamaged, _impl_.current_hp_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadZoneEnterNotification, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadZoneEnterNotification, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadZoneEnterNotification, _impl_.username_),
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadZoneEnterNotification, _impl_.position_),
        2,
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadZoneExitNotification, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadZoneExitNotification, _impl_.id_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Proto::PayloadTransformSync)},
        {9, sizeof(::Proto::PayloadPlayAction)},
        {20, sizeof(::Proto::PayloadEntityDamaged)},
        {29, sizeof(::Proto::PayloadZoneEnterNotification)},
        {38, sizeof(::Proto::PayloadZoneExitNotification)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Proto::_PayloadTransformSync_default_instance_._instance,
    &::Proto::_PayloadPlayAction_default_instance_._instance,
    &::Proto::_PayloadEntityDamaged_default_instance_._instance,
    &::Proto::_PayloadZoneEnterNotification_default_instance_._instance,
    &::Proto::_PayloadZoneExitNotification_default_instance_._instance,
};
const char descriptor_table_protodef_process_2fzone_2fsync_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027process/zone/sync.proto\022\005Proto\032\021common"
    "/math.proto\"W\n\024PayloadTransformSync\022\n\n\002i"
    "d\030\001 \001(\004\022\021\n\ttimestamp\030\002 \001(\004\022 \n\010position\030\003"
    " \001(\0132\016.Proto.Vector3\"X\n\021PayloadPlayActio"
    "n\022\n\n\002id\030\001 \001(\004\022\021\n\ttarget_id\030\002 \001(\004\022\021\n\tacti"
    "on_id\030\003 \001(\r\022\021\n\ttimestamp\030\004 \001(\003\"M\n\024Payloa"
    "dEntityDamaged\022\021\n\tentity_id\030\001 \001(\004\022\016\n\006dam"
    "age\030\002 \001(\005\022\022\n\ncurrent_hp\030\003 \001(\005\"^\n\034Payload"
    "ZoneEnterNotification\022\n\n\002id\030\001 \001(\004\022\020\n\010use"
    "rname\030\002 \001(\t\022 \n\010position\030\003 \001(\0132\016.Proto.Ve"
    "ctor3\")\n\033PayloadZoneExitNotification\022\n\n\002"
    "id\030\001 \001(\004b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_process_2fzone_2fsync_2eproto_deps[1] = {
        &::descriptor_table_common_2fmath_2eproto,
};
static ::absl::once_flag descriptor_table_process_2fzone_2fsync_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_process_2fzone_2fsync_2eproto = {
    false,
    false,
    456,
    descriptor_table_protodef_process_2fzone_2fsync_2eproto,
    "process/zone/sync.proto",
    &descriptor_table_process_2fzone_2fsync_2eproto_once,
    descriptor_table_process_2fzone_2fsync_2eproto_deps,
    1,
    5,
    schemas,
    file_default_instances,
    TableStruct_process_2fzone_2fsync_2eproto::offsets,
    file_level_enum_descriptors_process_2fzone_2fsync_2eproto,
    file_level_service_descriptors_process_2fzone_2fsync_2eproto,
};
namespace Proto {
// ===================================================================

class PayloadTransformSync::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PayloadTransformSync>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PayloadTransformSync, _impl_._has_bits_);
};

void PayloadTransformSync::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ != nullptr) _impl_.position_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
PayloadTransformSync::PayloadTransformSync(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadTransformSync_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.PayloadTransformSync)
}
PROTOBUF_NDEBUG_INLINE PayloadTransformSync::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Proto::PayloadTransformSync& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

PayloadTransformSync::PayloadTransformSync(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PayloadTransformSync& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadTransformSync_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PayloadTransformSync* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.position_ = ((cached_has_bits & 0x00000001U) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.position_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, timestamp_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::timestamp_));

  // @@protoc_insertion_point(copy_constructor:Proto.PayloadTransformSync)
}
PROTOBUF_NDEBUG_INLINE PayloadTransformSync::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PayloadTransformSync::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, position_),
           0,
           offsetof(Impl_, timestamp_) -
               offsetof(Impl_, position_) +
               sizeof(Impl_::timestamp_));
}
PayloadTransformSync::~PayloadTransformSync() {
  // @@protoc_insertion_point(destructor:Proto.PayloadTransformSync)
  SharedDtor(*this);
}
inline void PayloadTransformSync::SharedDtor(MessageLite& self) {
  PayloadTransformSync& this_ = static_cast<PayloadTransformSync&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.position_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PayloadTransformSync::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PayloadTransformSync(arena);
}
constexpr auto PayloadTransformSync::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PayloadTransformSync),
                                            alignof(PayloadTransformSync));
}
constexpr auto PayloadTransformSync::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PayloadTransformSync_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PayloadTransformSync::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PayloadTransformSync>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PayloadTransformSync::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PayloadTransformSync>(), &PayloadTransformSync::ByteSizeLong,
              &PayloadTransformSync::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PayloadTransformSync, _impl_._cached_size_),
          false,
      },
      &PayloadTransformSync::kDescriptorMethods,
      &descriptor_table_process_2fzone_2fsync_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PayloadTransformSync_class_data_ =
        PayloadTransformSync::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PayloadTransformSync::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PayloadTransformSync_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PayloadTransformSync_class_data_.tc_table);
  return PayloadTransformSync_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2>
PayloadTransformSync::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PayloadTransformSync, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PayloadTransformSync_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::PayloadTransformSync>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PayloadTransformSync, _impl_.id_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(PayloadTransformSync, _impl_.id_)}},
    // uint64 timestamp = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PayloadTransformSync, _impl_.timestamp_), 2>(),
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(PayloadTransformSync, _impl_.timestamp_)}},
    // .Proto.Vector3 position = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(PayloadTransformSync, _impl_.position_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 id = 1;
    {PROTOBUF_FIELD_OFFSET(PayloadTransformSync, _impl_.id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(PayloadTransformSync, _impl_.timestamp_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // .Proto.Vector3 position = 3;
    {PROTOBUF_FIELD_OFFSET(PayloadTransformSync, _impl_.position_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Proto::Vector3>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void PayloadTransformSync::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.PayloadTransformSync)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    ABSL_DCHECK(_impl_.position_ != nullptr);
    _impl_.position_->Clear();
  }
  if ((cached_has_bits & 0x00000006U) != 0) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.timestamp_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.timestamp_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PayloadTransformSync::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PayloadTransformSync& this_ = static_cast<const PayloadTransformSync&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PayloadTransformSync::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PayloadTransformSync& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.PayloadTransformSync)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (this_._internal_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_id(), target);
    }
  }

  // uint64 timestamp = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000004U) != 0) {
    if (this_._internal_timestamp() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_timestamp(), target);
    }
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // .Proto.Vector3 position = 3;
  if ((cached_has_bits & 0x00000001U) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.position_, this_._impl_.position_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.PayloadTransformSync)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PayloadTransformSync::ByteSizeLong(const MessageLite& base) {
  const PayloadTransformSync& this_ = static_cast<const PayloadTransformSync&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PayloadTransformSync::ByteSizeLong() const {
  const PayloadTransformSync& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.PayloadTransformSync)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    // .Proto.Vector3 position = 3;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.position_);
    }
    // uint64 id = 1;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_id());
      }
    }
    // uint64 timestamp = 2;
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_timestamp());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PayloadTransformSync::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PayloadTransformSync*>(&to_msg);
  auto& from = static_cast<const PayloadTransformSync&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.PayloadTransformSync)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      ABSL_DCHECK(from._impl_.position_ != nullptr);
      if (_this->_impl_.position_ == nullptr) {
        _this->_impl_.position_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.position_);
      } else {
        _this->_impl_.position_->MergeFrom(*from._impl_.position_);
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (from._internal_timestamp() != 0) {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadTransformSync::CopyFrom(const PayloadTransformSync& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.PayloadTransformSync)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PayloadTransformSync::InternalSwap(PayloadTransformSync* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PayloadTransformSync, _impl_.timestamp_)
      + sizeof(PayloadTransformSync::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(PayloadTransformSync, _impl_.position_)>(
          reinterpret_cast<char*>(&_impl_.position_),
          reinterpret_cast<char*>(&other->_impl_.position_));
}

::google::protobuf::Metadata PayloadTransformSync::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PayloadPlayAction::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PayloadPlayAction>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PayloadPlayAction, _impl_._has_bits_);
};

PayloadPlayAction::PayloadPlayAction(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadPlayAction_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.PayloadPlayAction)
}
PayloadPlayAction::PayloadPlayAction(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadPlayAction& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadPlayAction_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PayloadPlayAction::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PayloadPlayAction::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, action_id_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::action_id_));
}
PayloadPlayAction::~PayloadPlayAction() {
  // @@protoc_insertion_point(destructor:Proto.PayloadPlayAction)
  SharedDtor(*this);
}
inline void PayloadPlayAction::SharedDtor(MessageLite& self) {
  PayloadPlayAction& this_ = static_cast<PayloadPlayAction&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PayloadPlayAction::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PayloadPlayAction(arena);
}
constexpr auto PayloadPlayAction::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PayloadPlayAction),
                                            alignof(PayloadPlayAction));
}
constexpr auto PayloadPlayAction::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PayloadPlayAction_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PayloadPlayAction::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PayloadPlayAction>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PayloadPlayAction::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PayloadPlayAction>(), &PayloadPlayAction::ByteSizeLong,
              &PayloadPlayAction::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PayloadPlayAction, _impl_._cached_size_),
          false,
      },
      &PayloadPlayAction::kDescriptorMethods,
      &descriptor_table_process_2fzone_2fsync_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PayloadPlayAction_class_data_ =
        PayloadPlayAction::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PayloadPlayAction::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PayloadPlayAction_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PayloadPlayAction_class_data_.tc_table);
  return PayloadPlayAction_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
PayloadPlayAction::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PayloadPlayAction, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PayloadPlayAction_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::PayloadPlayAction>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 timestamp = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PayloadPlayAction, _impl_.timestamp_), 2>(),
     {32, 2, 0, PROTOBUF_FIELD_OFFSET(PayloadPlayAction, _impl_.timestamp_)}},
    // uint64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PayloadPlayAction, _impl_.id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PayloadPlayAction, _impl_.id_)}},
    // uint64 target_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PayloadPlayAction, _impl_.target_id_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(PayloadPlayAction, _impl_.target_id_)}},
    // uint32 action_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PayloadPlayAction, _impl_.action_id_), 3>(),
     {24, 3, 0, PROTOBUF_FIELD_OFFSET(PayloadPlayAction, _impl_.action_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 id = 1;
    {PROTOBUF_FIELD_OFFSET(PayloadPlayAction, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 target_id = 2;
    {PROTOBUF_FIELD_OFFSET(PayloadPlayAction, _impl_.target_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint32 action_id = 3;
    {PROTOBUF_FIELD_OFFSET(PayloadPlayAction, _impl_.action_id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // int64 timestamp = 4;
    {PROTOBUF_FIELD_OFFSET(PayloadPlayAction, _impl_.timestamp_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PayloadPlayAction::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.PayloadPlayAction)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fU) != 0) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.action_id_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.action_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PayloadPlayAction::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PayloadPlayAction& this_ = static_cast<const PayloadPlayAction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PayloadPlayAction::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PayloadPlayAction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.PayloadPlayAction)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_id(), target);
    }
  }

  // uint64 target_id = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (this_._internal_target_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_target_id(), target);
    }
  }

  // uint32 action_id = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000008U) != 0) {
    if (this_._internal_action_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_action_id(), target);
    }
  }

  // int64 timestamp = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000004U) != 0) {
    if (this_._internal_timestamp() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<4>(
              stream, this_._internal_timestamp(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.PayloadPlayAction)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PayloadPlayAction::ByteSizeLong(const MessageLite& base) {
  const PayloadPlayAction& this_ = static_cast<const PayloadPlayAction&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PayloadPlayAction::ByteSizeLong() const {
  const PayloadPlayAction& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.PayloadPlayAction)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fU) != 0) {
    // uint64 id = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_id());
      }
    }
    // uint64 target_id = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (this_._internal_target_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_target_id());
      }
    }
    // int64 timestamp = 4;
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp());
      }
    }
    // uint32 action_id = 3;
    if ((cached_has_bits & 0x00000008U) != 0) {
      if (this_._internal_action_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_action_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PayloadPlayAction::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PayloadPlayAction*>(&to_msg);
  auto& from = static_cast<const PayloadPlayAction&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.PayloadPlayAction)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fU) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (from._internal_target_id() != 0) {
        _this->_impl_.target_id_ = from._impl_.target_id_;
      }
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (from._internal_timestamp() != 0) {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
    if ((cached_has_bits & 0x00000008U) != 0) {
      if (from._internal_action_id() != 0) {
        _this->_impl_.action_id_ = from._impl_.action_id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadPlayAction::CopyFrom(const PayloadPlayAction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.PayloadPlayAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PayloadPlayAction::InternalSwap(PayloadPlayAction* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PayloadPlayAction, _impl_.action_id_)
      + sizeof(PayloadPlayAction::_impl_.action_id_)
      - PROTOBUF_FIELD_OFFSET(PayloadPlayAction, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata PayloadPlayAction::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PayloadEntityDamaged::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PayloadEntityDamaged>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PayloadEntityDamaged, _impl_._has_bits_);
};

PayloadEntityDamaged::PayloadEntityDamaged(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadEntityDamaged_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.PayloadEntityDamaged)
}
PayloadEntityDamaged::PayloadEntityDamaged(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadEntityDamaged& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadEntityDamaged_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PayloadEntityDamaged::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PayloadEntityDamaged::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, entity_id_),
           0,
           offsetof(Impl_, current_hp_) -
               offsetof(Impl_, entity_id_) +
               sizeof(Impl_::current_hp_));
}
PayloadEntityDamaged::~PayloadEntityDamaged() {
  // @@protoc_insertion_point(destructor:Proto.PayloadEntityDamaged)
  SharedDtor(*this);
}
inline void PayloadEntityDamaged::SharedDtor(MessageLite& self) {
  PayloadEntityDamaged& this_ = static_cast<PayloadEntityDamaged&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PayloadEntityDamaged::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PayloadEntityDamaged(arena);
}
constexpr auto PayloadEntityDamaged::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PayloadEntityDamaged),
                                            alignof(PayloadEntityDamaged));
}
constexpr auto PayloadEntityDamaged::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PayloadEntityDamaged_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PayloadEntityDamaged::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PayloadEntityDamaged>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PayloadEntityDamaged::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PayloadEntityDamaged>(), &PayloadEntityDamaged::ByteSizeLong,
              &PayloadEntityDamaged::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PayloadEntityDamaged, _impl_._cached_size_),
          false,
      },
      &PayloadEntityDamaged::kDescriptorMethods,
      &descriptor_table_process_2fzone_2fsync_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PayloadEntityDamaged_class_data_ =
        PayloadEntityDamaged::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PayloadEntityDamaged::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PayloadEntityDamaged_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PayloadEntityDamaged_class_data_.tc_table);
  return PayloadEntityDamaged_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
PayloadEntityDamaged::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PayloadEntityDamaged, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PayloadEntityDamaged_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::PayloadEntityDamaged>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 entity_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PayloadEntityDamaged, _impl_.entity_id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PayloadEntityDamaged, _impl_.entity_id_)}},
    // int32 damage = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PayloadEntityDamaged, _impl_.damage_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(PayloadEntityDamaged, _impl_.damage_)}},
    // int32 current_hp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PayloadEntityDamaged, _impl_.current_hp_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(PayloadEntityDamaged, _impl_.current_hp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 entity_id = 1;
    {PROTOBUF_FIELD_OFFSET(PayloadEntityDamaged, _impl_.entity_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // int32 damage = 2;
    {PROTOBUF_FIELD_OFFSET(PayloadEntityDamaged, _impl_.damage_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 current_hp = 3;
    {PROTOBUF_FIELD_OFFSET(PayloadEntityDamaged, _impl_.current_hp_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PayloadEntityDamaged::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.PayloadEntityDamaged)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    ::memset(&_impl_.entity_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.current_hp_) -
        reinterpret_cast<char*>(&_impl_.entity_id_)) + sizeof(_impl_.current_hp_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PayloadEntityDamaged::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PayloadEntityDamaged& this_ = static_cast<const PayloadEntityDamaged&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PayloadEntityDamaged::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PayloadEntityDamaged& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.PayloadEntityDamaged)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 entity_id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_entity_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_entity_id(), target);
    }
  }

  // int32 damage = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (this_._internal_damage() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_damage(), target);
    }
  }

  // int32 current_hp = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004U) != 0) {
    if (this_._internal_current_hp() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_current_hp(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.PayloadEntityDamaged)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PayloadEntityDamaged::ByteSizeLong(const MessageLite& base) {
  const PayloadEntityDamaged& this_ = static_cast<const PayloadEntityDamaged&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PayloadEntityDamaged::ByteSizeLong() const {
  const PayloadEntityDamaged& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.PayloadEntityDamaged)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    // uint64 entity_id = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_entity_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_entity_id());
      }
    }
    // int32 damage = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (this_._internal_damage() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_damage());
      }
    }
    // int32 current_hp = 3;
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (this_._internal_current_hp() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_current_hp());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PayloadEntityDamaged::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PayloadEntityDamaged*>(&to_msg);
  auto& from = static_cast<const PayloadEntityDamaged&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.PayloadEntityDamaged)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (from._internal_entity_id() != 0) {
        _this->_impl_.entity_id_ = from._impl_.entity_id_;
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (from._internal_damage() != 0) {
        _this->_impl_.damage_ = from._impl_.damage_;
      }
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (from._internal_current_hp() != 0) {
        _this->_impl_.current_hp_ = from._impl_.current_hp_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadEntityDamaged::CopyFrom(const PayloadEntityDamaged& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.PayloadEntityDamaged)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PayloadEntityDamaged::InternalSwap(PayloadEntityDamaged* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PayloadEntityDamaged, _impl_.current_hp_)
      + sizeof(PayloadEntityDamaged::_impl_.current_hp_)
      - PROTOBUF_FIELD_OFFSET(PayloadEntityDamaged, _impl_.entity_id_)>(
          reinterpret_cast<char*>(&_impl_.entity_id_),
          reinterpret_cast<char*>(&other->_impl_.entity_id_));
}

::google::protobuf::Metadata PayloadEntityDamaged::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PayloadZoneEnterNotification::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PayloadZoneEnterNotification>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PayloadZoneEnterNotification, _impl_._has_bits_);
};

void PayloadZoneEnterNotification::clear_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ != nullptr) _impl_.position_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
PayloadZoneEnterNotification::PayloadZoneEnterNotification(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadZoneEnterNotification_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.PayloadZoneEnterNotification)
}
PROTOBUF_NDEBUG_INLINE PayloadZoneEnterNotification::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Proto::PayloadZoneEnterNotification& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        username_(arena, from.username_) {}

PayloadZoneEnterNotification::PayloadZoneEnterNotification(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PayloadZoneEnterNotification& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadZoneEnterNotification_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PayloadZoneEnterNotification* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.position_ = ((cached_has_bits & 0x00000002U) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.position_)
                : nullptr;
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:Proto.PayloadZoneEnterNotification)
}
PROTOBUF_NDEBUG_INLINE PayloadZoneEnterNotification::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        username_(arena) {}

inline void PayloadZoneEnterNotification::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, position_),
           0,
           offsetof(Impl_, id_) -
               offsetof(Impl_, position_) +
               sizeof(Impl_::id_));
}
PayloadZoneEnterNotification::~PayloadZoneEnterNotification() {
  // @@protoc_insertion_point(destructor:Proto.PayloadZoneEnterNotification)
  SharedDtor(*this);
}
inline void PayloadZoneEnterNotification::SharedDtor(MessageLite& self) {
  PayloadZoneEnterNotification& this_ = static_cast<PayloadZoneEnterNotification&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.username_.Destroy();
  delete this_._impl_.position_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PayloadZoneEnterNotification::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PayloadZoneEnterNotification(arena);
}
constexpr auto PayloadZoneEnterNotification::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PayloadZoneEnterNotification),
                                            alignof(PayloadZoneEnterNotification));
}
constexpr auto PayloadZoneEnterNotification::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PayloadZoneEnterNotification_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PayloadZoneEnterNotification::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PayloadZoneEnterNotification>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PayloadZoneEnterNotification::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PayloadZoneEnterNotification>(), &PayloadZoneEnterNotification::ByteSizeLong,
              &PayloadZoneEnterNotification::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PayloadZoneEnterNotification, _impl_._cached_size_),
          false,
      },
      &PayloadZoneEnterNotification::kDescriptorMethods,
      &descriptor_table_process_2fzone_2fsync_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PayloadZoneEnterNotification_class_data_ =
        PayloadZoneEnterNotification::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PayloadZoneEnterNotification::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PayloadZoneEnterNotification_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PayloadZoneEnterNotification_class_data_.tc_table);
  return PayloadZoneEnterNotification_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 51, 2>
PayloadZoneEnterNotification::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PayloadZoneEnterNotification, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PayloadZoneEnterNotification_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::PayloadZoneEnterNotification>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PayloadZoneEnterNotification, _impl_.id_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(PayloadZoneEnterNotification, _impl_.id_)}},
    // string username = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(PayloadZoneEnterNotification, _impl_.username_)}},
    // .Proto.Vector3 position = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(PayloadZoneEnterNotification, _impl_.position_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 id = 1;
    {PROTOBUF_FIELD_OFFSET(PayloadZoneEnterNotification, _impl_.id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // string username = 2;
    {PROTOBUF_FIELD_OFFSET(PayloadZoneEnterNotification, _impl_.username_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .Proto.Vector3 position = 3;
    {PROTOBUF_FIELD_OFFSET(PayloadZoneEnterNotification, _impl_.position_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Proto::Vector3>()},
  }},
  {{
    "\42\0\10\0\0\0\0\0"
    "Proto.PayloadZoneEnterNotification"
    "username"
  }},
};
PROTOBUF_NOINLINE void PayloadZoneEnterNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.PayloadZoneEnterNotification)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _impl_.username_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      ABSL_DCHECK(_impl_.position_ != nullptr);
      _impl_.position_->Clear();
    }
  }
  _impl_.id_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PayloadZoneEnterNotification::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PayloadZoneEnterNotification& this_ = static_cast<const PayloadZoneEnterNotification&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PayloadZoneEnterNotification::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PayloadZoneEnterNotification& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.PayloadZoneEnterNotification)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000004U) != 0) {
    if (this_._internal_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_id(), target);
    }
  }

  // string username = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_username().empty()) {
      const ::std::string& _s = this_._internal_username();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Proto.PayloadZoneEnterNotification.username");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // .Proto.Vector3 position = 3;
  if ((cached_has_bits & 0x00000002U) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.position_, this_._impl_.position_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.PayloadZoneEnterNotification)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PayloadZoneEnterNotification::ByteSizeLong(const MessageLite& base) {
  const PayloadZoneEnterNotification& this_ = static_cast<const PayloadZoneEnterNotification&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PayloadZoneEnterNotification::ByteSizeLong() const {
  const PayloadZoneEnterNotification& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.PayloadZoneEnterNotification)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    // string username = 2;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_username().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_username());
      }
    }
    // .Proto.Vector3 position = 3;
    if ((cached_has_bits & 0x00000002U) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.position_);
    }
    // uint64 id = 1;
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PayloadZoneEnterNotification::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PayloadZoneEnterNotification*>(&to_msg);
  auto& from = static_cast<const PayloadZoneEnterNotification&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.PayloadZoneEnterNotification)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!from._internal_username().empty()) {
        _this->_internal_set_username(from._internal_username());
      } else {
        if (_this->_impl_.username_.IsDefault()) {
          _this->_internal_set_username("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      ABSL_DCHECK(from._impl_.position_ != nullptr);
      if (_this->_impl_.position_ == nullptr) {
        _this->_impl_.position_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.position_);
      } else {
        _this->_impl_.position_->MergeFrom(*from._impl_.position_);
      }
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadZoneEnterNotification::CopyFrom(const PayloadZoneEnterNotification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.PayloadZoneEnterNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PayloadZoneEnterNotification::InternalSwap(PayloadZoneEnterNotification* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.username_, &other->_impl_.username_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PayloadZoneEnterNotification, _impl_.id_)
      + sizeof(PayloadZoneEnterNotification::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(PayloadZoneEnterNotification, _impl_.position_)>(
          reinterpret_cast<char*>(&_impl_.position_),
          reinterpret_cast<char*>(&other->_impl_.position_));
}

::google::protobuf::Metadata PayloadZoneEnterNotification::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PayloadZoneExitNotification::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PayloadZoneExitNotification>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PayloadZoneExitNotification, _impl_._has_bits_);
};

PayloadZoneExitNotification::PayloadZoneExitNotification(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadZoneExitNotification_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.PayloadZoneExitNotification)
}
PayloadZoneExitNotification::PayloadZoneExitNotification(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadZoneExitNotification& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadZoneExitNotification_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PayloadZoneExitNotification::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PayloadZoneExitNotification::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
PayloadZoneExitNotification::~PayloadZoneExitNotification() {
  // @@protoc_insertion_point(destructor:Proto.PayloadZoneExitNotification)
  SharedDtor(*this);
}
inline void PayloadZoneExitNotification::SharedDtor(MessageLite& self) {
  PayloadZoneExitNotification& this_ = static_cast<PayloadZoneExitNotification&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PayloadZoneExitNotification::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PayloadZoneExitNotification(arena);
}
constexpr auto PayloadZoneExitNotification::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PayloadZoneExitNotification),
                                            alignof(PayloadZoneExitNotification));
}
constexpr auto PayloadZoneExitNotification::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PayloadZoneExitNotification_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PayloadZoneExitNotification::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PayloadZoneExitNotification>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PayloadZoneExitNotification::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PayloadZoneExitNotification>(), &PayloadZoneExitNotification::ByteSizeLong,
              &PayloadZoneExitNotification::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PayloadZoneExitNotification, _impl_._cached_size_),
          false,
      },
      &PayloadZoneExitNotification::kDescriptorMethods,
      &descriptor_table_process_2fzone_2fsync_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PayloadZoneExitNotification_class_data_ =
        PayloadZoneExitNotification::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PayloadZoneExitNotification::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PayloadZoneExitNotification_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PayloadZoneExitNotification_class_data_.tc_table);
  return PayloadZoneExitNotification_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
PayloadZoneExitNotification::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PayloadZoneExitNotification, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PayloadZoneExitNotification_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::PayloadZoneExitNotification>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PayloadZoneExitNotification, _impl_.id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PayloadZoneExitNotification, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 id = 1;
    {PROTOBUF_FIELD_OFFSET(PayloadZoneExitNotification, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PayloadZoneExitNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.PayloadZoneExitNotification)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PayloadZoneExitNotification::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PayloadZoneExitNotification& this_ = static_cast<const PayloadZoneExitNotification&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PayloadZoneExitNotification::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PayloadZoneExitNotification& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.PayloadZoneExitNotification)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.PayloadZoneExitNotification)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PayloadZoneExitNotification::ByteSizeLong(const MessageLite& base) {
  const PayloadZoneExitNotification& this_ = static_cast<const PayloadZoneExitNotification&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PayloadZoneExitNotification::ByteSizeLong() const {
  const PayloadZoneExitNotification& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.PayloadZoneExitNotification)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // uint64 id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PayloadZoneExitNotification::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PayloadZoneExitNotification*>(&to_msg);
  auto& from = static_cast<const PayloadZoneExitNotification&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.PayloadZoneExitNotification)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (from._internal_id() != 0) {
      _this->_impl_.id_ = from._impl_.id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadZoneExitNotification::CopyFrom(const PayloadZoneExitNotification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.PayloadZoneExitNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PayloadZoneExitNotification::InternalSwap(PayloadZoneExitNotification* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata PayloadZoneExitNotification::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_process_2fzone_2fsync_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
