// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/login/logout.proto
// Protobuf C++ Version: 6.32.1

#include "process/login/logout.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Proto {

inline constexpr PayloadLogoutResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        is_succeeded_{false} {}

template <typename>
PROTOBUF_CONSTEXPR PayloadLogoutResponse::PayloadLogoutResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PayloadLogoutResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PayloadLogoutResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadLogoutResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadLogoutResponseDefaultTypeInternal() {}
  union {
    PayloadLogoutResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadLogoutResponseDefaultTypeInternal _PayloadLogoutResponse_default_instance_;

inline constexpr PayloadLogoutRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR PayloadLogoutRequest::PayloadLogoutRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PayloadLogoutRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PayloadLogoutRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadLogoutRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadLogoutRequestDefaultTypeInternal() {}
  union {
    PayloadLogoutRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadLogoutRequestDefaultTypeInternal _PayloadLogoutRequest_default_instance_;

inline constexpr PayloadLogoutNotification::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR PayloadLogoutNotification::PayloadLogoutNotification(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PayloadLogoutNotification_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PayloadLogoutNotificationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadLogoutNotificationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadLogoutNotificationDefaultTypeInternal() {}
  union {
    PayloadLogoutNotification _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadLogoutNotificationDefaultTypeInternal _PayloadLogoutNotification_default_instance_;
}  // namespace Proto
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_process_2flogin_2flogout_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_process_2flogin_2flogout_2eproto = nullptr;
const ::uint32_t
    TableStruct_process_2flogin_2flogout_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadLogoutRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadLogoutRequest, _impl_.id_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadLogoutResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadLogoutResponse, _impl_.is_succeeded_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadLogoutNotification, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadLogoutNotification, _impl_.id_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Proto::PayloadLogoutRequest)},
        {5, sizeof(::Proto::PayloadLogoutResponse)},
        {10, sizeof(::Proto::PayloadLogoutNotification)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Proto::_PayloadLogoutRequest_default_instance_._instance,
    &::Proto::_PayloadLogoutResponse_default_instance_._instance,
    &::Proto::_PayloadLogoutNotification_default_instance_._instance,
};
const char descriptor_table_protodef_process_2flogin_2flogout_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032process/login/logout.proto\022\005Proto\"\"\n\024P"
    "ayloadLogoutRequest\022\n\n\002id\030\001 \001(\004\"-\n\025Paylo"
    "adLogoutResponse\022\024\n\014is_succeeded\030\001 \001(\010\"\'"
    "\n\031PayloadLogoutNotification\022\n\n\002id\030\001 \001(\004*"
    "Y\n\025CategoryLogoutMessage\022\022\n\016LOGOUT_REQUE"
    "ST\020\000\022\023\n\017LOGOUT_RESPONSE\020\001\022\027\n\023LOGOUT_NOTI"
    "FICATION\020\002b\006proto3"
};
static ::absl::once_flag descriptor_table_process_2flogin_2flogout_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_process_2flogin_2flogout_2eproto = {
    false,
    false,
    258,
    descriptor_table_protodef_process_2flogin_2flogout_2eproto,
    "process/login/logout.proto",
    &descriptor_table_process_2flogin_2flogout_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_process_2flogin_2flogout_2eproto::offsets,
    file_level_enum_descriptors_process_2flogin_2flogout_2eproto,
    file_level_service_descriptors_process_2flogin_2flogout_2eproto,
};
namespace Proto {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CategoryLogoutMessage_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_process_2flogin_2flogout_2eproto);
  return file_level_enum_descriptors_process_2flogin_2flogout_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CategoryLogoutMessage_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class PayloadLogoutRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PayloadLogoutRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PayloadLogoutRequest, _impl_._has_bits_);
};

PayloadLogoutRequest::PayloadLogoutRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadLogoutRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.PayloadLogoutRequest)
}
PayloadLogoutRequest::PayloadLogoutRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadLogoutRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadLogoutRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PayloadLogoutRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PayloadLogoutRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
PayloadLogoutRequest::~PayloadLogoutRequest() {
  // @@protoc_insertion_point(destructor:Proto.PayloadLogoutRequest)
  SharedDtor(*this);
}
inline void PayloadLogoutRequest::SharedDtor(MessageLite& self) {
  PayloadLogoutRequest& this_ = static_cast<PayloadLogoutRequest&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PayloadLogoutRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PayloadLogoutRequest(arena);
}
constexpr auto PayloadLogoutRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PayloadLogoutRequest),
                                            alignof(PayloadLogoutRequest));
}
constexpr auto PayloadLogoutRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PayloadLogoutRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PayloadLogoutRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PayloadLogoutRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PayloadLogoutRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PayloadLogoutRequest>(), &PayloadLogoutRequest::ByteSizeLong,
              &PayloadLogoutRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PayloadLogoutRequest, _impl_._cached_size_),
          false,
      },
      &PayloadLogoutRequest::kDescriptorMethods,
      &descriptor_table_process_2flogin_2flogout_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PayloadLogoutRequest_class_data_ =
        PayloadLogoutRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PayloadLogoutRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PayloadLogoutRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PayloadLogoutRequest_class_data_.tc_table);
  return PayloadLogoutRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
PayloadLogoutRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PayloadLogoutRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PayloadLogoutRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::PayloadLogoutRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PayloadLogoutRequest, _impl_.id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PayloadLogoutRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 id = 1;
    {PROTOBUF_FIELD_OFFSET(PayloadLogoutRequest, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PayloadLogoutRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.PayloadLogoutRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PayloadLogoutRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PayloadLogoutRequest& this_ = static_cast<const PayloadLogoutRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PayloadLogoutRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PayloadLogoutRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.PayloadLogoutRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.PayloadLogoutRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PayloadLogoutRequest::ByteSizeLong(const MessageLite& base) {
  const PayloadLogoutRequest& this_ = static_cast<const PayloadLogoutRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PayloadLogoutRequest::ByteSizeLong() const {
  const PayloadLogoutRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.PayloadLogoutRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // uint64 id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PayloadLogoutRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PayloadLogoutRequest*>(&to_msg);
  auto& from = static_cast<const PayloadLogoutRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.PayloadLogoutRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (from._internal_id() != 0) {
      _this->_impl_.id_ = from._impl_.id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadLogoutRequest::CopyFrom(const PayloadLogoutRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.PayloadLogoutRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PayloadLogoutRequest::InternalSwap(PayloadLogoutRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata PayloadLogoutRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PayloadLogoutResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PayloadLogoutResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PayloadLogoutResponse, _impl_._has_bits_);
};

PayloadLogoutResponse::PayloadLogoutResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadLogoutResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.PayloadLogoutResponse)
}
PayloadLogoutResponse::PayloadLogoutResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadLogoutResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadLogoutResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PayloadLogoutResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PayloadLogoutResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.is_succeeded_ = {};
}
PayloadLogoutResponse::~PayloadLogoutResponse() {
  // @@protoc_insertion_point(destructor:Proto.PayloadLogoutResponse)
  SharedDtor(*this);
}
inline void PayloadLogoutResponse::SharedDtor(MessageLite& self) {
  PayloadLogoutResponse& this_ = static_cast<PayloadLogoutResponse&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PayloadLogoutResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PayloadLogoutResponse(arena);
}
constexpr auto PayloadLogoutResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PayloadLogoutResponse),
                                            alignof(PayloadLogoutResponse));
}
constexpr auto PayloadLogoutResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PayloadLogoutResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PayloadLogoutResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PayloadLogoutResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PayloadLogoutResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PayloadLogoutResponse>(), &PayloadLogoutResponse::ByteSizeLong,
              &PayloadLogoutResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PayloadLogoutResponse, _impl_._cached_size_),
          false,
      },
      &PayloadLogoutResponse::kDescriptorMethods,
      &descriptor_table_process_2flogin_2flogout_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PayloadLogoutResponse_class_data_ =
        PayloadLogoutResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PayloadLogoutResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PayloadLogoutResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PayloadLogoutResponse_class_data_.tc_table);
  return PayloadLogoutResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
PayloadLogoutResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PayloadLogoutResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PayloadLogoutResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::PayloadLogoutResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool is_succeeded = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PayloadLogoutResponse, _impl_.is_succeeded_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PayloadLogoutResponse, _impl_.is_succeeded_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool is_succeeded = 1;
    {PROTOBUF_FIELD_OFFSET(PayloadLogoutResponse, _impl_.is_succeeded_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PayloadLogoutResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.PayloadLogoutResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.is_succeeded_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PayloadLogoutResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PayloadLogoutResponse& this_ = static_cast<const PayloadLogoutResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PayloadLogoutResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PayloadLogoutResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.PayloadLogoutResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool is_succeeded = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_is_succeeded() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_is_succeeded(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.PayloadLogoutResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PayloadLogoutResponse::ByteSizeLong(const MessageLite& base) {
  const PayloadLogoutResponse& this_ = static_cast<const PayloadLogoutResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PayloadLogoutResponse::ByteSizeLong() const {
  const PayloadLogoutResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.PayloadLogoutResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // bool is_succeeded = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_is_succeeded() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PayloadLogoutResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PayloadLogoutResponse*>(&to_msg);
  auto& from = static_cast<const PayloadLogoutResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.PayloadLogoutResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (from._internal_is_succeeded() != 0) {
      _this->_impl_.is_succeeded_ = from._impl_.is_succeeded_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadLogoutResponse::CopyFrom(const PayloadLogoutResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.PayloadLogoutResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PayloadLogoutResponse::InternalSwap(PayloadLogoutResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.is_succeeded_, other->_impl_.is_succeeded_);
}

::google::protobuf::Metadata PayloadLogoutResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PayloadLogoutNotification::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PayloadLogoutNotification>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PayloadLogoutNotification, _impl_._has_bits_);
};

PayloadLogoutNotification::PayloadLogoutNotification(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadLogoutNotification_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.PayloadLogoutNotification)
}
PayloadLogoutNotification::PayloadLogoutNotification(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadLogoutNotification& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadLogoutNotification_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PayloadLogoutNotification::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PayloadLogoutNotification::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
PayloadLogoutNotification::~PayloadLogoutNotification() {
  // @@protoc_insertion_point(destructor:Proto.PayloadLogoutNotification)
  SharedDtor(*this);
}
inline void PayloadLogoutNotification::SharedDtor(MessageLite& self) {
  PayloadLogoutNotification& this_ = static_cast<PayloadLogoutNotification&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PayloadLogoutNotification::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PayloadLogoutNotification(arena);
}
constexpr auto PayloadLogoutNotification::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PayloadLogoutNotification),
                                            alignof(PayloadLogoutNotification));
}
constexpr auto PayloadLogoutNotification::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PayloadLogoutNotification_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PayloadLogoutNotification::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PayloadLogoutNotification>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PayloadLogoutNotification::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PayloadLogoutNotification>(), &PayloadLogoutNotification::ByteSizeLong,
              &PayloadLogoutNotification::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PayloadLogoutNotification, _impl_._cached_size_),
          false,
      },
      &PayloadLogoutNotification::kDescriptorMethods,
      &descriptor_table_process_2flogin_2flogout_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PayloadLogoutNotification_class_data_ =
        PayloadLogoutNotification::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PayloadLogoutNotification::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PayloadLogoutNotification_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PayloadLogoutNotification_class_data_.tc_table);
  return PayloadLogoutNotification_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
PayloadLogoutNotification::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PayloadLogoutNotification, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PayloadLogoutNotification_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::PayloadLogoutNotification>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PayloadLogoutNotification, _impl_.id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PayloadLogoutNotification, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 id = 1;
    {PROTOBUF_FIELD_OFFSET(PayloadLogoutNotification, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PayloadLogoutNotification::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.PayloadLogoutNotification)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PayloadLogoutNotification::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PayloadLogoutNotification& this_ = static_cast<const PayloadLogoutNotification&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PayloadLogoutNotification::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PayloadLogoutNotification& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.PayloadLogoutNotification)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.PayloadLogoutNotification)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PayloadLogoutNotification::ByteSizeLong(const MessageLite& base) {
  const PayloadLogoutNotification& this_ = static_cast<const PayloadLogoutNotification&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PayloadLogoutNotification::ByteSizeLong() const {
  const PayloadLogoutNotification& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.PayloadLogoutNotification)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // uint64 id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PayloadLogoutNotification::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PayloadLogoutNotification*>(&to_msg);
  auto& from = static_cast<const PayloadLogoutNotification&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.PayloadLogoutNotification)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (from._internal_id() != 0) {
      _this->_impl_.id_ = from._impl_.id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadLogoutNotification::CopyFrom(const PayloadLogoutNotification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.PayloadLogoutNotification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PayloadLogoutNotification::InternalSwap(PayloadLogoutNotification* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata PayloadLogoutNotification::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_process_2flogin_2flogout_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
