// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/world/packet.proto
// Protobuf C++ Version: 6.32.1

#ifndef process_2fworld_2fpacket_2eproto_2epb_2eh
#define process_2fworld_2fpacket_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "process/world/player_route.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_process_2fworld_2fpacket_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_process_2fworld_2fpacket_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_process_2fworld_2fpacket_2eproto;
}  // extern "C"
namespace Proto {
class WorldPacket;
struct WorldPacketDefaultTypeInternal;
extern WorldPacketDefaultTypeInternal _WorldPacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull WorldPacket_class_data_;
}  // namespace Proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Proto {

// ===================================================================


// -------------------------------------------------------------------

class WorldPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Proto.WorldPacket) */ {
 public:
  inline WorldPacket() : WorldPacket(nullptr) {}
  ~WorldPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WorldPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WorldPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WorldPacket(::google::protobuf::internal::ConstantInitialized);

  inline WorldPacket(const WorldPacket& from) : WorldPacket(nullptr, from) {}
  inline WorldPacket(WorldPacket&& from) noexcept
      : WorldPacket(nullptr, ::std::move(from)) {}
  inline WorldPacket& operator=(const WorldPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline WorldPacket& operator=(WorldPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WorldPacket& default_instance() {
    return *reinterpret_cast<const WorldPacket*>(
        &_WorldPacket_default_instance_);
  }
  enum MessageCase {
    kZoneEnterRequest = 1,
    kZoneEnterResponse = 2,
    kZoneExit = 3,
    MESSAGE_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(WorldPacket& a, WorldPacket& b) { a.Swap(&b); }
  inline void Swap(WorldPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WorldPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WorldPacket* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WorldPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WorldPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WorldPacket& from) { WorldPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WorldPacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Proto.WorldPacket"; }

 protected:
  explicit WorldPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  WorldPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WorldPacket& from);
  WorldPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, WorldPacket&& from) noexcept
      : WorldPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kZoneEnterRequestFieldNumber = 1,
    kZoneEnterResponseFieldNumber = 2,
    kZoneExitFieldNumber = 3,
  };
  // .Proto.PayloadZoneEnterRequest zone_enter_request = 1;
  bool has_zone_enter_request() const;
  private:
  bool _internal_has_zone_enter_request() const;

  public:
  void clear_zone_enter_request() ;
  const ::Proto::PayloadZoneEnterRequest& zone_enter_request() const;
  [[nodiscard]] ::Proto::PayloadZoneEnterRequest* PROTOBUF_NULLABLE release_zone_enter_request();
  ::Proto::PayloadZoneEnterRequest* PROTOBUF_NONNULL mutable_zone_enter_request();
  void set_allocated_zone_enter_request(::Proto::PayloadZoneEnterRequest* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_zone_enter_request(::Proto::PayloadZoneEnterRequest* PROTOBUF_NULLABLE value);
  ::Proto::PayloadZoneEnterRequest* PROTOBUF_NULLABLE unsafe_arena_release_zone_enter_request();

  private:
  const ::Proto::PayloadZoneEnterRequest& _internal_zone_enter_request() const;
  ::Proto::PayloadZoneEnterRequest* PROTOBUF_NONNULL _internal_mutable_zone_enter_request();

  public:
  // .Proto.PayloadZoneEnterResponse zone_enter_response = 2;
  bool has_zone_enter_response() const;
  private:
  bool _internal_has_zone_enter_response() const;

  public:
  void clear_zone_enter_response() ;
  const ::Proto::PayloadZoneEnterResponse& zone_enter_response() const;
  [[nodiscard]] ::Proto::PayloadZoneEnterResponse* PROTOBUF_NULLABLE release_zone_enter_response();
  ::Proto::PayloadZoneEnterResponse* PROTOBUF_NONNULL mutable_zone_enter_response();
  void set_allocated_zone_enter_response(::Proto::PayloadZoneEnterResponse* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_zone_enter_response(::Proto::PayloadZoneEnterResponse* PROTOBUF_NULLABLE value);
  ::Proto::PayloadZoneEnterResponse* PROTOBUF_NULLABLE unsafe_arena_release_zone_enter_response();

  private:
  const ::Proto::PayloadZoneEnterResponse& _internal_zone_enter_response() const;
  ::Proto::PayloadZoneEnterResponse* PROTOBUF_NONNULL _internal_mutable_zone_enter_response();

  public:
  // .Proto.PayloadZoneExit zone_exit = 3;
  bool has_zone_exit() const;
  private:
  bool _internal_has_zone_exit() const;

  public:
  void clear_zone_exit() ;
  const ::Proto::PayloadZoneExit& zone_exit() const;
  [[nodiscard]] ::Proto::PayloadZoneExit* PROTOBUF_NULLABLE release_zone_exit();
  ::Proto::PayloadZoneExit* PROTOBUF_NONNULL mutable_zone_exit();
  void set_allocated_zone_exit(::Proto::PayloadZoneExit* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_zone_exit(::Proto::PayloadZoneExit* PROTOBUF_NULLABLE value);
  ::Proto::PayloadZoneExit* PROTOBUF_NULLABLE unsafe_arena_release_zone_exit();

  private:
  const ::Proto::PayloadZoneExit& _internal_zone_exit() const;
  ::Proto::PayloadZoneExit* PROTOBUF_NONNULL _internal_mutable_zone_exit();

  public:
  void clear_message();
  MessageCase message_case() const;
  // @@protoc_insertion_point(class_scope:Proto.WorldPacket)
 private:
  class _Internal;
  void set_has_zone_enter_request();
  void set_has_zone_enter_response();
  void set_has_zone_exit();
  inline bool has_message() const;
  inline void clear_has_message();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 3,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const WorldPacket& from_msg);
    union MessageUnion {
      constexpr MessageUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE zone_enter_request_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE zone_enter_response_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE zone_exit_;
    } message_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_process_2fworld_2fpacket_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull WorldPacket_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// WorldPacket

// .Proto.PayloadZoneEnterRequest zone_enter_request = 1;
inline bool WorldPacket::has_zone_enter_request() const {
  return message_case() == kZoneEnterRequest;
}
inline bool WorldPacket::_internal_has_zone_enter_request() const {
  return message_case() == kZoneEnterRequest;
}
inline void WorldPacket::set_has_zone_enter_request() {
  _impl_._oneof_case_[0] = kZoneEnterRequest;
}
inline ::Proto::PayloadZoneEnterRequest* PROTOBUF_NULLABLE WorldPacket::release_zone_enter_request() {
  // @@protoc_insertion_point(field_release:Proto.WorldPacket.zone_enter_request)
  if (message_case() == kZoneEnterRequest) {
    clear_has_message();
    auto* temp = reinterpret_cast<::Proto::PayloadZoneEnterRequest*>(_impl_.message_.zone_enter_request_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.message_.zone_enter_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Proto::PayloadZoneEnterRequest& WorldPacket::_internal_zone_enter_request() const {
  return message_case() == kZoneEnterRequest ? *reinterpret_cast<::Proto::PayloadZoneEnterRequest*>(_impl_.message_.zone_enter_request_) : reinterpret_cast<::Proto::PayloadZoneEnterRequest&>(::Proto::_PayloadZoneEnterRequest_default_instance_);
}
inline const ::Proto::PayloadZoneEnterRequest& WorldPacket::zone_enter_request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Proto.WorldPacket.zone_enter_request)
  return _internal_zone_enter_request();
}
inline ::Proto::PayloadZoneEnterRequest* PROTOBUF_NULLABLE WorldPacket::unsafe_arena_release_zone_enter_request() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Proto.WorldPacket.zone_enter_request)
  if (message_case() == kZoneEnterRequest) {
    clear_has_message();
    auto* temp = reinterpret_cast<::Proto::PayloadZoneEnterRequest*>(_impl_.message_.zone_enter_request_);
    _impl_.message_.zone_enter_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void WorldPacket::unsafe_arena_set_allocated_zone_enter_request(
    ::Proto::PayloadZoneEnterRequest* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_message();
  if (value) {
    set_has_zone_enter_request();
    _impl_.message_.zone_enter_request_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.WorldPacket.zone_enter_request)
}
inline ::Proto::PayloadZoneEnterRequest* PROTOBUF_NONNULL WorldPacket::_internal_mutable_zone_enter_request() {
  if (message_case() != kZoneEnterRequest) {
    clear_message();
    set_has_zone_enter_request();
    _impl_.message_.zone_enter_request_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Proto::PayloadZoneEnterRequest>(GetArena()));
  }
  return reinterpret_cast<::Proto::PayloadZoneEnterRequest*>(_impl_.message_.zone_enter_request_);
}
inline ::Proto::PayloadZoneEnterRequest* PROTOBUF_NONNULL WorldPacket::mutable_zone_enter_request()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Proto::PayloadZoneEnterRequest* _msg = _internal_mutable_zone_enter_request();
  // @@protoc_insertion_point(field_mutable:Proto.WorldPacket.zone_enter_request)
  return _msg;
}

// .Proto.PayloadZoneEnterResponse zone_enter_response = 2;
inline bool WorldPacket::has_zone_enter_response() const {
  return message_case() == kZoneEnterResponse;
}
inline bool WorldPacket::_internal_has_zone_enter_response() const {
  return message_case() == kZoneEnterResponse;
}
inline void WorldPacket::set_has_zone_enter_response() {
  _impl_._oneof_case_[0] = kZoneEnterResponse;
}
inline ::Proto::PayloadZoneEnterResponse* PROTOBUF_NULLABLE WorldPacket::release_zone_enter_response() {
  // @@protoc_insertion_point(field_release:Proto.WorldPacket.zone_enter_response)
  if (message_case() == kZoneEnterResponse) {
    clear_has_message();
    auto* temp = reinterpret_cast<::Proto::PayloadZoneEnterResponse*>(_impl_.message_.zone_enter_response_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.message_.zone_enter_response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Proto::PayloadZoneEnterResponse& WorldPacket::_internal_zone_enter_response() const {
  return message_case() == kZoneEnterResponse ? *reinterpret_cast<::Proto::PayloadZoneEnterResponse*>(_impl_.message_.zone_enter_response_) : reinterpret_cast<::Proto::PayloadZoneEnterResponse&>(::Proto::_PayloadZoneEnterResponse_default_instance_);
}
inline const ::Proto::PayloadZoneEnterResponse& WorldPacket::zone_enter_response() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Proto.WorldPacket.zone_enter_response)
  return _internal_zone_enter_response();
}
inline ::Proto::PayloadZoneEnterResponse* PROTOBUF_NULLABLE WorldPacket::unsafe_arena_release_zone_enter_response() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Proto.WorldPacket.zone_enter_response)
  if (message_case() == kZoneEnterResponse) {
    clear_has_message();
    auto* temp = reinterpret_cast<::Proto::PayloadZoneEnterResponse*>(_impl_.message_.zone_enter_response_);
    _impl_.message_.zone_enter_response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void WorldPacket::unsafe_arena_set_allocated_zone_enter_response(
    ::Proto::PayloadZoneEnterResponse* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_message();
  if (value) {
    set_has_zone_enter_response();
    _impl_.message_.zone_enter_response_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.WorldPacket.zone_enter_response)
}
inline ::Proto::PayloadZoneEnterResponse* PROTOBUF_NONNULL WorldPacket::_internal_mutable_zone_enter_response() {
  if (message_case() != kZoneEnterResponse) {
    clear_message();
    set_has_zone_enter_response();
    _impl_.message_.zone_enter_response_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Proto::PayloadZoneEnterResponse>(GetArena()));
  }
  return reinterpret_cast<::Proto::PayloadZoneEnterResponse*>(_impl_.message_.zone_enter_response_);
}
inline ::Proto::PayloadZoneEnterResponse* PROTOBUF_NONNULL WorldPacket::mutable_zone_enter_response()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Proto::PayloadZoneEnterResponse* _msg = _internal_mutable_zone_enter_response();
  // @@protoc_insertion_point(field_mutable:Proto.WorldPacket.zone_enter_response)
  return _msg;
}

// .Proto.PayloadZoneExit zone_exit = 3;
inline bool WorldPacket::has_zone_exit() const {
  return message_case() == kZoneExit;
}
inline bool WorldPacket::_internal_has_zone_exit() const {
  return message_case() == kZoneExit;
}
inline void WorldPacket::set_has_zone_exit() {
  _impl_._oneof_case_[0] = kZoneExit;
}
inline ::Proto::PayloadZoneExit* PROTOBUF_NULLABLE WorldPacket::release_zone_exit() {
  // @@protoc_insertion_point(field_release:Proto.WorldPacket.zone_exit)
  if (message_case() == kZoneExit) {
    clear_has_message();
    auto* temp = reinterpret_cast<::Proto::PayloadZoneExit*>(_impl_.message_.zone_exit_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.message_.zone_exit_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Proto::PayloadZoneExit& WorldPacket::_internal_zone_exit() const {
  return message_case() == kZoneExit ? *reinterpret_cast<::Proto::PayloadZoneExit*>(_impl_.message_.zone_exit_) : reinterpret_cast<::Proto::PayloadZoneExit&>(::Proto::_PayloadZoneExit_default_instance_);
}
inline const ::Proto::PayloadZoneExit& WorldPacket::zone_exit() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Proto.WorldPacket.zone_exit)
  return _internal_zone_exit();
}
inline ::Proto::PayloadZoneExit* PROTOBUF_NULLABLE WorldPacket::unsafe_arena_release_zone_exit() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Proto.WorldPacket.zone_exit)
  if (message_case() == kZoneExit) {
    clear_has_message();
    auto* temp = reinterpret_cast<::Proto::PayloadZoneExit*>(_impl_.message_.zone_exit_);
    _impl_.message_.zone_exit_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void WorldPacket::unsafe_arena_set_allocated_zone_exit(
    ::Proto::PayloadZoneExit* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_message();
  if (value) {
    set_has_zone_exit();
    _impl_.message_.zone_exit_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.WorldPacket.zone_exit)
}
inline ::Proto::PayloadZoneExit* PROTOBUF_NONNULL WorldPacket::_internal_mutable_zone_exit() {
  if (message_case() != kZoneExit) {
    clear_message();
    set_has_zone_exit();
    _impl_.message_.zone_exit_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Proto::PayloadZoneExit>(GetArena()));
  }
  return reinterpret_cast<::Proto::PayloadZoneExit*>(_impl_.message_.zone_exit_);
}
inline ::Proto::PayloadZoneExit* PROTOBUF_NONNULL WorldPacket::mutable_zone_exit()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Proto::PayloadZoneExit* _msg = _internal_mutable_zone_exit();
  // @@protoc_insertion_point(field_mutable:Proto.WorldPacket.zone_exit)
  return _msg;
}

inline bool WorldPacket::has_message() const {
  return message_case() != MESSAGE_NOT_SET;
}
inline void WorldPacket::clear_has_message() {
  _impl_._oneof_case_[0] = MESSAGE_NOT_SET;
}
inline WorldPacket::MessageCase WorldPacket::message_case() const {
  return WorldPacket::MessageCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // process_2fworld_2fpacket_2eproto_2epb_2eh
