// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/world/player_route.proto
// Protobuf C++ Version: 6.32.1

#ifndef process_2fworld_2fplayer_5froute_2eproto_2epb_2eh
#define process_2fworld_2fplayer_5froute_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "common/math.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_process_2fworld_2fplayer_5froute_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_process_2fworld_2fplayer_5froute_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_process_2fworld_2fplayer_5froute_2eproto;
}  // extern "C"
namespace Proto {
enum CategoryWorldMessage : int;
extern const uint32_t CategoryWorldMessage_internal_data_[];
class PayloadZoneEnterRequest;
struct PayloadZoneEnterRequestDefaultTypeInternal;
extern PayloadZoneEnterRequestDefaultTypeInternal _PayloadZoneEnterRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PayloadZoneEnterRequest_class_data_;
class PayloadZoneEnterResponse;
struct PayloadZoneEnterResponseDefaultTypeInternal;
extern PayloadZoneEnterResponseDefaultTypeInternal _PayloadZoneEnterResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PayloadZoneEnterResponse_class_data_;
class PayloadZoneExit;
struct PayloadZoneExitDefaultTypeInternal;
extern PayloadZoneExitDefaultTypeInternal _PayloadZoneExit_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PayloadZoneExit_class_data_;
}  // namespace Proto
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::Proto::CategoryWorldMessage_internal_data_>
    internal::EnumTraitsImpl::value<::Proto::CategoryWorldMessage>;
}  // namespace protobuf
}  // namespace google

namespace Proto {
enum CategoryWorldMessage : int {
  ZONE_ENTER_REQUEST = 0,
  ZONE_ENTER_RESPONSE = 1,
  ZONE_EXIT = 2,
  CategoryWorldMessage_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  CategoryWorldMessage_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t CategoryWorldMessage_internal_data_[];
inline constexpr CategoryWorldMessage CategoryWorldMessage_MIN =
    static_cast<CategoryWorldMessage>(0);
inline constexpr CategoryWorldMessage CategoryWorldMessage_MAX =
    static_cast<CategoryWorldMessage>(2);
inline bool CategoryWorldMessage_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int CategoryWorldMessage_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CategoryWorldMessage_descriptor();
template <typename T>
const ::std::string& CategoryWorldMessage_Name(T value) {
  static_assert(::std::is_same<T, CategoryWorldMessage>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to CategoryWorldMessage_Name().");
  return CategoryWorldMessage_Name(static_cast<CategoryWorldMessage>(value));
}
template <>
inline const ::std::string& CategoryWorldMessage_Name(CategoryWorldMessage value) {
  return ::google::protobuf::internal::NameOfDenseEnum<CategoryWorldMessage_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool CategoryWorldMessage_Parse(
    ::absl::string_view name, CategoryWorldMessage* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<CategoryWorldMessage>(CategoryWorldMessage_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class PayloadZoneEnterRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Proto.PayloadZoneEnterRequest) */ {
 public:
  inline PayloadZoneEnterRequest() : PayloadZoneEnterRequest(nullptr) {}
  ~PayloadZoneEnterRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PayloadZoneEnterRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PayloadZoneEnterRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PayloadZoneEnterRequest(::google::protobuf::internal::ConstantInitialized);

  inline PayloadZoneEnterRequest(const PayloadZoneEnterRequest& from) : PayloadZoneEnterRequest(nullptr, from) {}
  inline PayloadZoneEnterRequest(PayloadZoneEnterRequest&& from) noexcept
      : PayloadZoneEnterRequest(nullptr, ::std::move(from)) {}
  inline PayloadZoneEnterRequest& operator=(const PayloadZoneEnterRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PayloadZoneEnterRequest& operator=(PayloadZoneEnterRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PayloadZoneEnterRequest& default_instance() {
    return *reinterpret_cast<const PayloadZoneEnterRequest*>(
        &_PayloadZoneEnterRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PayloadZoneEnterRequest& a, PayloadZoneEnterRequest& b) { a.Swap(&b); }
  inline void Swap(PayloadZoneEnterRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PayloadZoneEnterRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PayloadZoneEnterRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PayloadZoneEnterRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PayloadZoneEnterRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PayloadZoneEnterRequest& from) { PayloadZoneEnterRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PayloadZoneEnterRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Proto.PayloadZoneEnterRequest"; }

 protected:
  explicit PayloadZoneEnterRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PayloadZoneEnterRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadZoneEnterRequest& from);
  PayloadZoneEnterRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PayloadZoneEnterRequest&& from) noexcept
      : PayloadZoneEnterRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kZoneNameFieldNumber = 2,
    kPlayerIdFieldNumber = 1,
  };
  // string zone_name = 2;
  void clear_zone_name() ;
  const ::std::string& zone_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_zone_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_zone_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_zone_name();
  void set_allocated_zone_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_zone_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_zone_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_zone_name();

  public:
  // uint64 player_id = 1;
  void clear_player_id() ;
  ::uint64_t player_id() const;
  void set_player_id(::uint64_t value);

  private:
  ::uint64_t _internal_player_id() const;
  void _internal_set_player_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Proto.PayloadZoneEnterRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 47,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PayloadZoneEnterRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr zone_name_;
    ::uint64_t player_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_process_2fworld_2fplayer_5froute_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PayloadZoneEnterRequest_class_data_;
// -------------------------------------------------------------------

class PayloadZoneExit final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Proto.PayloadZoneExit) */ {
 public:
  inline PayloadZoneExit() : PayloadZoneExit(nullptr) {}
  ~PayloadZoneExit() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PayloadZoneExit* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PayloadZoneExit));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PayloadZoneExit(::google::protobuf::internal::ConstantInitialized);

  inline PayloadZoneExit(const PayloadZoneExit& from) : PayloadZoneExit(nullptr, from) {}
  inline PayloadZoneExit(PayloadZoneExit&& from) noexcept
      : PayloadZoneExit(nullptr, ::std::move(from)) {}
  inline PayloadZoneExit& operator=(const PayloadZoneExit& from) {
    CopyFrom(from);
    return *this;
  }
  inline PayloadZoneExit& operator=(PayloadZoneExit&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PayloadZoneExit& default_instance() {
    return *reinterpret_cast<const PayloadZoneExit*>(
        &_PayloadZoneExit_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PayloadZoneExit& a, PayloadZoneExit& b) { a.Swap(&b); }
  inline void Swap(PayloadZoneExit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PayloadZoneExit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PayloadZoneExit* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PayloadZoneExit>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PayloadZoneExit& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PayloadZoneExit& from) { PayloadZoneExit::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PayloadZoneExit* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Proto.PayloadZoneExit"; }

 protected:
  explicit PayloadZoneExit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PayloadZoneExit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadZoneExit& from);
  PayloadZoneExit(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PayloadZoneExit&& from) noexcept
      : PayloadZoneExit(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kZoneNameFieldNumber = 2,
    kLastPositionFieldNumber = 3,
    kPlayerIdFieldNumber = 1,
  };
  // string zone_name = 2;
  void clear_zone_name() ;
  const ::std::string& zone_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_zone_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_zone_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_zone_name();
  void set_allocated_zone_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_zone_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_zone_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_zone_name();

  public:
  // .Proto.Vector3 last_position = 3;
  bool has_last_position() const;
  void clear_last_position() ;
  const ::Proto::Vector3& last_position() const;
  [[nodiscard]] ::Proto::Vector3* PROTOBUF_NULLABLE release_last_position();
  ::Proto::Vector3* PROTOBUF_NONNULL mutable_last_position();
  void set_allocated_last_position(::Proto::Vector3* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_last_position(::Proto::Vector3* PROTOBUF_NULLABLE value);
  ::Proto::Vector3* PROTOBUF_NULLABLE unsafe_arena_release_last_position();

  private:
  const ::Proto::Vector3& _internal_last_position() const;
  ::Proto::Vector3* PROTOBUF_NONNULL _internal_mutable_last_position();

  public:
  // uint64 player_id = 1;
  void clear_player_id() ;
  ::uint64_t player_id() const;
  void set_player_id(::uint64_t value);

  private:
  ::uint64_t _internal_player_id() const;
  void _internal_set_player_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Proto.PayloadZoneExit)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 39,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PayloadZoneExit& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr zone_name_;
    ::Proto::Vector3* PROTOBUF_NULLABLE last_position_;
    ::uint64_t player_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_process_2fworld_2fplayer_5froute_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PayloadZoneExit_class_data_;
// -------------------------------------------------------------------

class PayloadZoneEnterResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Proto.PayloadZoneEnterResponse) */ {
 public:
  inline PayloadZoneEnterResponse() : PayloadZoneEnterResponse(nullptr) {}
  ~PayloadZoneEnterResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PayloadZoneEnterResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PayloadZoneEnterResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PayloadZoneEnterResponse(::google::protobuf::internal::ConstantInitialized);

  inline PayloadZoneEnterResponse(const PayloadZoneEnterResponse& from) : PayloadZoneEnterResponse(nullptr, from) {}
  inline PayloadZoneEnterResponse(PayloadZoneEnterResponse&& from) noexcept
      : PayloadZoneEnterResponse(nullptr, ::std::move(from)) {}
  inline PayloadZoneEnterResponse& operator=(const PayloadZoneEnterResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PayloadZoneEnterResponse& operator=(PayloadZoneEnterResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PayloadZoneEnterResponse& default_instance() {
    return *reinterpret_cast<const PayloadZoneEnterResponse*>(
        &_PayloadZoneEnterResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PayloadZoneEnterResponse& a, PayloadZoneEnterResponse& b) { a.Swap(&b); }
  inline void Swap(PayloadZoneEnterResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PayloadZoneEnterResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PayloadZoneEnterResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PayloadZoneEnterResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PayloadZoneEnterResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PayloadZoneEnterResponse& from) { PayloadZoneEnterResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PayloadZoneEnterResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Proto.PayloadZoneEnterResponse"; }

 protected:
  explicit PayloadZoneEnterResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PayloadZoneEnterResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadZoneEnterResponse& from);
  PayloadZoneEnterResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PayloadZoneEnterResponse&& from) noexcept
      : PayloadZoneEnterResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPositionFieldNumber = 3,
    kPlayerIdFieldNumber = 1,
    kIsSucceededFieldNumber = 2,
  };
  // .Proto.Vector3 position = 3;
  bool has_position() const;
  void clear_position() ;
  const ::Proto::Vector3& position() const;
  [[nodiscard]] ::Proto::Vector3* PROTOBUF_NULLABLE release_position();
  ::Proto::Vector3* PROTOBUF_NONNULL mutable_position();
  void set_allocated_position(::Proto::Vector3* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_position(::Proto::Vector3* PROTOBUF_NULLABLE value);
  ::Proto::Vector3* PROTOBUF_NULLABLE unsafe_arena_release_position();

  private:
  const ::Proto::Vector3& _internal_position() const;
  ::Proto::Vector3* PROTOBUF_NONNULL _internal_mutable_position();

  public:
  // uint64 player_id = 1;
  void clear_player_id() ;
  ::uint64_t player_id() const;
  void set_player_id(::uint64_t value);

  private:
  ::uint64_t _internal_player_id() const;
  void _internal_set_player_id(::uint64_t value);

  public:
  // bool is_succeeded = 2;
  void clear_is_succeeded() ;
  bool is_succeeded() const;
  void set_is_succeeded(bool value);

  private:
  bool _internal_is_succeeded() const;
  void _internal_set_is_succeeded(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Proto.PayloadZoneEnterResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PayloadZoneEnterResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Proto::Vector3* PROTOBUF_NULLABLE position_;
    ::uint64_t player_id_;
    bool is_succeeded_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_process_2fworld_2fplayer_5froute_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PayloadZoneEnterResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PayloadZoneEnterRequest

// uint64 player_id = 1;
inline void PayloadZoneEnterRequest::clear_player_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint64_t PayloadZoneEnterRequest::player_id() const {
  // @@protoc_insertion_point(field_get:Proto.PayloadZoneEnterRequest.player_id)
  return _internal_player_id();
}
inline void PayloadZoneEnterRequest::set_player_id(::uint64_t value) {
  _internal_set_player_id(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:Proto.PayloadZoneEnterRequest.player_id)
}
inline ::uint64_t PayloadZoneEnterRequest::_internal_player_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.player_id_;
}
inline void PayloadZoneEnterRequest::_internal_set_player_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_id_ = value;
}

// string zone_name = 2;
inline void PayloadZoneEnterRequest::clear_zone_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.zone_name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& PayloadZoneEnterRequest::zone_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Proto.PayloadZoneEnterRequest.zone_name)
  return _internal_zone_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PayloadZoneEnterRequest::set_zone_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.zone_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Proto.PayloadZoneEnterRequest.zone_name)
}
inline ::std::string* PROTOBUF_NONNULL PayloadZoneEnterRequest::mutable_zone_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_zone_name();
  // @@protoc_insertion_point(field_mutable:Proto.PayloadZoneEnterRequest.zone_name)
  return _s;
}
inline const ::std::string& PayloadZoneEnterRequest::_internal_zone_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.zone_name_.Get();
}
inline void PayloadZoneEnterRequest::_internal_set_zone_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.zone_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PayloadZoneEnterRequest::_internal_mutable_zone_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.zone_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PayloadZoneEnterRequest::release_zone_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Proto.PayloadZoneEnterRequest.zone_name)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.zone_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.zone_name_.Set("", GetArena());
  }
  return released;
}
inline void PayloadZoneEnterRequest::set_allocated_zone_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.zone_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.zone_name_.IsDefault()) {
    _impl_.zone_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.PayloadZoneEnterRequest.zone_name)
}

// -------------------------------------------------------------------

// PayloadZoneEnterResponse

// uint64 player_id = 1;
inline void PayloadZoneEnterResponse::clear_player_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint64_t PayloadZoneEnterResponse::player_id() const {
  // @@protoc_insertion_point(field_get:Proto.PayloadZoneEnterResponse.player_id)
  return _internal_player_id();
}
inline void PayloadZoneEnterResponse::set_player_id(::uint64_t value) {
  _internal_set_player_id(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:Proto.PayloadZoneEnterResponse.player_id)
}
inline ::uint64_t PayloadZoneEnterResponse::_internal_player_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.player_id_;
}
inline void PayloadZoneEnterResponse::_internal_set_player_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_id_ = value;
}

// bool is_succeeded = 2;
inline void PayloadZoneEnterResponse::clear_is_succeeded() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_succeeded_ = false;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline bool PayloadZoneEnterResponse::is_succeeded() const {
  // @@protoc_insertion_point(field_get:Proto.PayloadZoneEnterResponse.is_succeeded)
  return _internal_is_succeeded();
}
inline void PayloadZoneEnterResponse::set_is_succeeded(bool value) {
  _internal_set_is_succeeded(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:Proto.PayloadZoneEnterResponse.is_succeeded)
}
inline bool PayloadZoneEnterResponse::_internal_is_succeeded() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_succeeded_;
}
inline void PayloadZoneEnterResponse::_internal_set_is_succeeded(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_succeeded_ = value;
}

// .Proto.Vector3 position = 3;
inline bool PayloadZoneEnterResponse::has_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.position_ != nullptr);
  return value;
}
inline const ::Proto::Vector3& PayloadZoneEnterResponse::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Proto::Vector3* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::Vector3&>(::Proto::_Vector3_default_instance_);
}
inline const ::Proto::Vector3& PayloadZoneEnterResponse::position() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Proto.PayloadZoneEnterResponse.position)
  return _internal_position();
}
inline void PayloadZoneEnterResponse::unsafe_arena_set_allocated_position(
    ::Proto::Vector3* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = reinterpret_cast<::Proto::Vector3*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.PayloadZoneEnterResponse.position)
}
inline ::Proto::Vector3* PROTOBUF_NULLABLE PayloadZoneEnterResponse::release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::Proto::Vector3* released = _impl_.position_;
  _impl_.position_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Proto::Vector3* PROTOBUF_NULLABLE PayloadZoneEnterResponse::unsafe_arena_release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Proto.PayloadZoneEnterResponse.position)

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::Proto::Vector3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::Proto::Vector3* PROTOBUF_NONNULL PayloadZoneEnterResponse::_internal_mutable_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Proto::Vector3>(GetArena());
    _impl_.position_ = reinterpret_cast<::Proto::Vector3*>(p);
  }
  return _impl_.position_;
}
inline ::Proto::Vector3* PROTOBUF_NONNULL PayloadZoneEnterResponse::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001U;
  ::Proto::Vector3* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:Proto.PayloadZoneEnterResponse.position)
  return _msg;
}
inline void PayloadZoneEnterResponse::set_allocated_position(::Proto::Vector3* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }

  _impl_.position_ = reinterpret_cast<::Proto::Vector3*>(value);
  // @@protoc_insertion_point(field_set_allocated:Proto.PayloadZoneEnterResponse.position)
}

// -------------------------------------------------------------------

// PayloadZoneExit

// uint64 player_id = 1;
inline void PayloadZoneExit::clear_player_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline ::uint64_t PayloadZoneExit::player_id() const {
  // @@protoc_insertion_point(field_get:Proto.PayloadZoneExit.player_id)
  return _internal_player_id();
}
inline void PayloadZoneExit::set_player_id(::uint64_t value) {
  _internal_set_player_id(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:Proto.PayloadZoneExit.player_id)
}
inline ::uint64_t PayloadZoneExit::_internal_player_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.player_id_;
}
inline void PayloadZoneExit::_internal_set_player_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_id_ = value;
}

// string zone_name = 2;
inline void PayloadZoneExit::clear_zone_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.zone_name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& PayloadZoneExit::zone_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Proto.PayloadZoneExit.zone_name)
  return _internal_zone_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PayloadZoneExit::set_zone_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.zone_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Proto.PayloadZoneExit.zone_name)
}
inline ::std::string* PROTOBUF_NONNULL PayloadZoneExit::mutable_zone_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_zone_name();
  // @@protoc_insertion_point(field_mutable:Proto.PayloadZoneExit.zone_name)
  return _s;
}
inline const ::std::string& PayloadZoneExit::_internal_zone_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.zone_name_.Get();
}
inline void PayloadZoneExit::_internal_set_zone_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.zone_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PayloadZoneExit::_internal_mutable_zone_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.zone_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PayloadZoneExit::release_zone_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Proto.PayloadZoneExit.zone_name)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.zone_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.zone_name_.Set("", GetArena());
  }
  return released;
}
inline void PayloadZoneExit::set_allocated_zone_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.zone_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.zone_name_.IsDefault()) {
    _impl_.zone_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Proto.PayloadZoneExit.zone_name)
}

// .Proto.Vector3 last_position = 3;
inline bool PayloadZoneExit::has_last_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.last_position_ != nullptr);
  return value;
}
inline const ::Proto::Vector3& PayloadZoneExit::_internal_last_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Proto::Vector3* p = _impl_.last_position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::Vector3&>(::Proto::_Vector3_default_instance_);
}
inline const ::Proto::Vector3& PayloadZoneExit::last_position() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Proto.PayloadZoneExit.last_position)
  return _internal_last_position();
}
inline void PayloadZoneExit::unsafe_arena_set_allocated_last_position(
    ::Proto::Vector3* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.last_position_);
  }
  _impl_.last_position_ = reinterpret_cast<::Proto::Vector3*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.PayloadZoneExit.last_position)
}
inline ::Proto::Vector3* PROTOBUF_NULLABLE PayloadZoneExit::release_last_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002U;
  ::Proto::Vector3* released = _impl_.last_position_;
  _impl_.last_position_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Proto::Vector3* PROTOBUF_NULLABLE PayloadZoneExit::unsafe_arena_release_last_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Proto.PayloadZoneExit.last_position)

  _impl_._has_bits_[0] &= ~0x00000002U;
  ::Proto::Vector3* temp = _impl_.last_position_;
  _impl_.last_position_ = nullptr;
  return temp;
}
inline ::Proto::Vector3* PROTOBUF_NONNULL PayloadZoneExit::_internal_mutable_last_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.last_position_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Proto::Vector3>(GetArena());
    _impl_.last_position_ = reinterpret_cast<::Proto::Vector3*>(p);
  }
  return _impl_.last_position_;
}
inline ::Proto::Vector3* PROTOBUF_NONNULL PayloadZoneExit::mutable_last_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002U;
  ::Proto::Vector3* _msg = _internal_mutable_last_position();
  // @@protoc_insertion_point(field_mutable:Proto.PayloadZoneExit.last_position)
  return _msg;
}
inline void PayloadZoneExit::set_allocated_last_position(::Proto::Vector3* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.last_position_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }

  _impl_.last_position_ = reinterpret_cast<::Proto::Vector3*>(value);
  // @@protoc_insertion_point(field_set_allocated:Proto.PayloadZoneExit.last_position)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Proto::CategoryWorldMessage> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Proto::CategoryWorldMessage>() {
  return ::Proto::CategoryWorldMessage_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // process_2fworld_2fplayer_5froute_2eproto_2epb_2eh
