// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/world/player_route.proto
// Protobuf C++ Version: 6.32.1

#ifndef process_2fworld_2fplayer_5froute_2eproto_2epb_2eh
#define process_2fworld_2fplayer_5froute_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "process/world/route_player_data.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_process_2fworld_2fplayer_5froute_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_process_2fworld_2fplayer_5froute_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_process_2fworld_2fplayer_5froute_2eproto;
}  // extern "C"
namespace Proto {
class PayloadPlayerExitZoneBegin;
struct PayloadPlayerExitZoneBeginDefaultTypeInternal;
extern PayloadPlayerExitZoneBeginDefaultTypeInternal _PayloadPlayerExitZoneBegin_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerExitZoneBegin_class_data_;
class PayloadPlayerExitZoneComplete;
struct PayloadPlayerExitZoneCompleteDefaultTypeInternal;
extern PayloadPlayerExitZoneCompleteDefaultTypeInternal _PayloadPlayerExitZoneComplete_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerExitZoneComplete_class_data_;
class PayloadPlayerExitZoneReady;
struct PayloadPlayerExitZoneReadyDefaultTypeInternal;
extern PayloadPlayerExitZoneReadyDefaultTypeInternal _PayloadPlayerExitZoneReady_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerExitZoneReady_class_data_;
class PayloadPlayerZoneEnterBegin;
struct PayloadPlayerZoneEnterBeginDefaultTypeInternal;
extern PayloadPlayerZoneEnterBeginDefaultTypeInternal _PayloadPlayerZoneEnterBegin_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerZoneEnterBegin_class_data_;
class PayloadPlayerZoneEnterComplete;
struct PayloadPlayerZoneEnterCompleteDefaultTypeInternal;
extern PayloadPlayerZoneEnterCompleteDefaultTypeInternal _PayloadPlayerZoneEnterComplete_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerZoneEnterComplete_class_data_;
class PayloadPlayerZoneEnterReady;
struct PayloadPlayerZoneEnterReadyDefaultTypeInternal;
extern PayloadPlayerZoneEnterReadyDefaultTypeInternal _PayloadPlayerZoneEnterReady_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerZoneEnterReady_class_data_;
class PayloadPlayerZoneEnterReadyResponse;
struct PayloadPlayerZoneEnterReadyResponseDefaultTypeInternal;
extern PayloadPlayerZoneEnterReadyResponseDefaultTypeInternal _PayloadPlayerZoneEnterReadyResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerZoneEnterReadyResponse_class_data_;
}  // namespace Proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Proto {

// ===================================================================


// -------------------------------------------------------------------

class PayloadPlayerZoneEnterReady final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Proto.PayloadPlayerZoneEnterReady) */ {
 public:
  inline PayloadPlayerZoneEnterReady() : PayloadPlayerZoneEnterReady(nullptr) {}
  ~PayloadPlayerZoneEnterReady() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PayloadPlayerZoneEnterReady* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PayloadPlayerZoneEnterReady));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PayloadPlayerZoneEnterReady(::google::protobuf::internal::ConstantInitialized);

  inline PayloadPlayerZoneEnterReady(const PayloadPlayerZoneEnterReady& from) : PayloadPlayerZoneEnterReady(nullptr, from) {}
  inline PayloadPlayerZoneEnterReady(PayloadPlayerZoneEnterReady&& from) noexcept
      : PayloadPlayerZoneEnterReady(nullptr, ::std::move(from)) {}
  inline PayloadPlayerZoneEnterReady& operator=(const PayloadPlayerZoneEnterReady& from) {
    CopyFrom(from);
    return *this;
  }
  inline PayloadPlayerZoneEnterReady& operator=(PayloadPlayerZoneEnterReady&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PayloadPlayerZoneEnterReady& default_instance() {
    return *reinterpret_cast<const PayloadPlayerZoneEnterReady*>(
        &_PayloadPlayerZoneEnterReady_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PayloadPlayerZoneEnterReady& a, PayloadPlayerZoneEnterReady& b) { a.Swap(&b); }
  inline void Swap(PayloadPlayerZoneEnterReady* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PayloadPlayerZoneEnterReady* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PayloadPlayerZoneEnterReady* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PayloadPlayerZoneEnterReady>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PayloadPlayerZoneEnterReady& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PayloadPlayerZoneEnterReady& from) { PayloadPlayerZoneEnterReady::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PayloadPlayerZoneEnterReady* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Proto.PayloadPlayerZoneEnterReady"; }

 protected:
  explicit PayloadPlayerZoneEnterReady(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PayloadPlayerZoneEnterReady(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadPlayerZoneEnterReady& from);
  PayloadPlayerZoneEnterReady(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PayloadPlayerZoneEnterReady&& from) noexcept
      : PayloadPlayerZoneEnterReady(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIdFieldNumber = 1,
  };
  // uint64 user_id = 1;
  void clear_user_id() ;
  ::uint64_t user_id() const;
  void set_user_id(::uint64_t value);

  private:
  ::uint64_t _internal_user_id() const;
  void _internal_set_user_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Proto.PayloadPlayerZoneEnterReady)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PayloadPlayerZoneEnterReady& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t user_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_process_2fworld_2fplayer_5froute_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerZoneEnterReady_class_data_;
// -------------------------------------------------------------------

class PayloadPlayerZoneEnterComplete final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Proto.PayloadPlayerZoneEnterComplete) */ {
 public:
  inline PayloadPlayerZoneEnterComplete() : PayloadPlayerZoneEnterComplete(nullptr) {}
  ~PayloadPlayerZoneEnterComplete() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PayloadPlayerZoneEnterComplete* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PayloadPlayerZoneEnterComplete));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PayloadPlayerZoneEnterComplete(::google::protobuf::internal::ConstantInitialized);

  inline PayloadPlayerZoneEnterComplete(const PayloadPlayerZoneEnterComplete& from) : PayloadPlayerZoneEnterComplete(nullptr, from) {}
  inline PayloadPlayerZoneEnterComplete(PayloadPlayerZoneEnterComplete&& from) noexcept
      : PayloadPlayerZoneEnterComplete(nullptr, ::std::move(from)) {}
  inline PayloadPlayerZoneEnterComplete& operator=(const PayloadPlayerZoneEnterComplete& from) {
    CopyFrom(from);
    return *this;
  }
  inline PayloadPlayerZoneEnterComplete& operator=(PayloadPlayerZoneEnterComplete&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PayloadPlayerZoneEnterComplete& default_instance() {
    return *reinterpret_cast<const PayloadPlayerZoneEnterComplete*>(
        &_PayloadPlayerZoneEnterComplete_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PayloadPlayerZoneEnterComplete& a, PayloadPlayerZoneEnterComplete& b) { a.Swap(&b); }
  inline void Swap(PayloadPlayerZoneEnterComplete* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PayloadPlayerZoneEnterComplete* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PayloadPlayerZoneEnterComplete* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PayloadPlayerZoneEnterComplete>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PayloadPlayerZoneEnterComplete& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PayloadPlayerZoneEnterComplete& from) { PayloadPlayerZoneEnterComplete::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PayloadPlayerZoneEnterComplete* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Proto.PayloadPlayerZoneEnterComplete"; }

 protected:
  explicit PayloadPlayerZoneEnterComplete(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PayloadPlayerZoneEnterComplete(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadPlayerZoneEnterComplete& from);
  PayloadPlayerZoneEnterComplete(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PayloadPlayerZoneEnterComplete&& from) noexcept
      : PayloadPlayerZoneEnterComplete(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIdFieldNumber = 1,
  };
  // uint64 user_id = 1;
  void clear_user_id() ;
  ::uint64_t user_id() const;
  void set_user_id(::uint64_t value);

  private:
  ::uint64_t _internal_user_id() const;
  void _internal_set_user_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Proto.PayloadPlayerZoneEnterComplete)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PayloadPlayerZoneEnterComplete& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t user_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_process_2fworld_2fplayer_5froute_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerZoneEnterComplete_class_data_;
// -------------------------------------------------------------------

class PayloadPlayerZoneEnterBegin final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Proto.PayloadPlayerZoneEnterBegin) */ {
 public:
  inline PayloadPlayerZoneEnterBegin() : PayloadPlayerZoneEnterBegin(nullptr) {}
  ~PayloadPlayerZoneEnterBegin() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PayloadPlayerZoneEnterBegin* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PayloadPlayerZoneEnterBegin));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PayloadPlayerZoneEnterBegin(::google::protobuf::internal::ConstantInitialized);

  inline PayloadPlayerZoneEnterBegin(const PayloadPlayerZoneEnterBegin& from) : PayloadPlayerZoneEnterBegin(nullptr, from) {}
  inline PayloadPlayerZoneEnterBegin(PayloadPlayerZoneEnterBegin&& from) noexcept
      : PayloadPlayerZoneEnterBegin(nullptr, ::std::move(from)) {}
  inline PayloadPlayerZoneEnterBegin& operator=(const PayloadPlayerZoneEnterBegin& from) {
    CopyFrom(from);
    return *this;
  }
  inline PayloadPlayerZoneEnterBegin& operator=(PayloadPlayerZoneEnterBegin&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PayloadPlayerZoneEnterBegin& default_instance() {
    return *reinterpret_cast<const PayloadPlayerZoneEnterBegin*>(
        &_PayloadPlayerZoneEnterBegin_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PayloadPlayerZoneEnterBegin& a, PayloadPlayerZoneEnterBegin& b) { a.Swap(&b); }
  inline void Swap(PayloadPlayerZoneEnterBegin* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PayloadPlayerZoneEnterBegin* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PayloadPlayerZoneEnterBegin* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PayloadPlayerZoneEnterBegin>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PayloadPlayerZoneEnterBegin& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PayloadPlayerZoneEnterBegin& from) { PayloadPlayerZoneEnterBegin::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PayloadPlayerZoneEnterBegin* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Proto.PayloadPlayerZoneEnterBegin"; }

 protected:
  explicit PayloadPlayerZoneEnterBegin(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PayloadPlayerZoneEnterBegin(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadPlayerZoneEnterBegin& from);
  PayloadPlayerZoneEnterBegin(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PayloadPlayerZoneEnterBegin&& from) noexcept
      : PayloadPlayerZoneEnterBegin(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIdFieldNumber = 1,
    kGatewayIdFieldNumber = 2,
  };
  // uint64 user_id = 1;
  void clear_user_id() ;
  ::uint64_t user_id() const;
  void set_user_id(::uint64_t value);

  private:
  ::uint64_t _internal_user_id() const;
  void _internal_set_user_id(::uint64_t value);

  public:
  // uint64 gateway_id = 2;
  void clear_gateway_id() ;
  ::uint64_t gateway_id() const;
  void set_gateway_id(::uint64_t value);

  private:
  ::uint64_t _internal_gateway_id() const;
  void _internal_set_gateway_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Proto.PayloadPlayerZoneEnterBegin)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PayloadPlayerZoneEnterBegin& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t user_id_;
    ::uint64_t gateway_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_process_2fworld_2fplayer_5froute_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerZoneEnterBegin_class_data_;
// -------------------------------------------------------------------

class PayloadPlayerExitZoneReady final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Proto.PayloadPlayerExitZoneReady) */ {
 public:
  inline PayloadPlayerExitZoneReady() : PayloadPlayerExitZoneReady(nullptr) {}
  ~PayloadPlayerExitZoneReady() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PayloadPlayerExitZoneReady* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PayloadPlayerExitZoneReady));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PayloadPlayerExitZoneReady(::google::protobuf::internal::ConstantInitialized);

  inline PayloadPlayerExitZoneReady(const PayloadPlayerExitZoneReady& from) : PayloadPlayerExitZoneReady(nullptr, from) {}
  inline PayloadPlayerExitZoneReady(PayloadPlayerExitZoneReady&& from) noexcept
      : PayloadPlayerExitZoneReady(nullptr, ::std::move(from)) {}
  inline PayloadPlayerExitZoneReady& operator=(const PayloadPlayerExitZoneReady& from) {
    CopyFrom(from);
    return *this;
  }
  inline PayloadPlayerExitZoneReady& operator=(PayloadPlayerExitZoneReady&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PayloadPlayerExitZoneReady& default_instance() {
    return *reinterpret_cast<const PayloadPlayerExitZoneReady*>(
        &_PayloadPlayerExitZoneReady_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(PayloadPlayerExitZoneReady& a, PayloadPlayerExitZoneReady& b) { a.Swap(&b); }
  inline void Swap(PayloadPlayerExitZoneReady* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PayloadPlayerExitZoneReady* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PayloadPlayerExitZoneReady* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PayloadPlayerExitZoneReady>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PayloadPlayerExitZoneReady& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PayloadPlayerExitZoneReady& from) { PayloadPlayerExitZoneReady::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PayloadPlayerExitZoneReady* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Proto.PayloadPlayerExitZoneReady"; }

 protected:
  explicit PayloadPlayerExitZoneReady(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PayloadPlayerExitZoneReady(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadPlayerExitZoneReady& from);
  PayloadPlayerExitZoneReady(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PayloadPlayerExitZoneReady&& from) noexcept
      : PayloadPlayerExitZoneReady(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIdFieldNumber = 1,
  };
  // uint64 user_id = 1;
  void clear_user_id() ;
  ::uint64_t user_id() const;
  void set_user_id(::uint64_t value);

  private:
  ::uint64_t _internal_user_id() const;
  void _internal_set_user_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Proto.PayloadPlayerExitZoneReady)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PayloadPlayerExitZoneReady& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t user_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_process_2fworld_2fplayer_5froute_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerExitZoneReady_class_data_;
// -------------------------------------------------------------------

class PayloadPlayerExitZoneComplete final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Proto.PayloadPlayerExitZoneComplete) */ {
 public:
  inline PayloadPlayerExitZoneComplete() : PayloadPlayerExitZoneComplete(nullptr) {}
  ~PayloadPlayerExitZoneComplete() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PayloadPlayerExitZoneComplete* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PayloadPlayerExitZoneComplete));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PayloadPlayerExitZoneComplete(::google::protobuf::internal::ConstantInitialized);

  inline PayloadPlayerExitZoneComplete(const PayloadPlayerExitZoneComplete& from) : PayloadPlayerExitZoneComplete(nullptr, from) {}
  inline PayloadPlayerExitZoneComplete(PayloadPlayerExitZoneComplete&& from) noexcept
      : PayloadPlayerExitZoneComplete(nullptr, ::std::move(from)) {}
  inline PayloadPlayerExitZoneComplete& operator=(const PayloadPlayerExitZoneComplete& from) {
    CopyFrom(from);
    return *this;
  }
  inline PayloadPlayerExitZoneComplete& operator=(PayloadPlayerExitZoneComplete&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PayloadPlayerExitZoneComplete& default_instance() {
    return *reinterpret_cast<const PayloadPlayerExitZoneComplete*>(
        &_PayloadPlayerExitZoneComplete_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(PayloadPlayerExitZoneComplete& a, PayloadPlayerExitZoneComplete& b) { a.Swap(&b); }
  inline void Swap(PayloadPlayerExitZoneComplete* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PayloadPlayerExitZoneComplete* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PayloadPlayerExitZoneComplete* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PayloadPlayerExitZoneComplete>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PayloadPlayerExitZoneComplete& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PayloadPlayerExitZoneComplete& from) { PayloadPlayerExitZoneComplete::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PayloadPlayerExitZoneComplete* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Proto.PayloadPlayerExitZoneComplete"; }

 protected:
  explicit PayloadPlayerExitZoneComplete(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PayloadPlayerExitZoneComplete(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadPlayerExitZoneComplete& from);
  PayloadPlayerExitZoneComplete(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PayloadPlayerExitZoneComplete&& from) noexcept
      : PayloadPlayerExitZoneComplete(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIdFieldNumber = 1,
  };
  // uint64 user_id = 1;
  void clear_user_id() ;
  ::uint64_t user_id() const;
  void set_user_id(::uint64_t value);

  private:
  ::uint64_t _internal_user_id() const;
  void _internal_set_user_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Proto.PayloadPlayerExitZoneComplete)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PayloadPlayerExitZoneComplete& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t user_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_process_2fworld_2fplayer_5froute_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerExitZoneComplete_class_data_;
// -------------------------------------------------------------------

class PayloadPlayerExitZoneBegin final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Proto.PayloadPlayerExitZoneBegin) */ {
 public:
  inline PayloadPlayerExitZoneBegin() : PayloadPlayerExitZoneBegin(nullptr) {}
  ~PayloadPlayerExitZoneBegin() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PayloadPlayerExitZoneBegin* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PayloadPlayerExitZoneBegin));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PayloadPlayerExitZoneBegin(::google::protobuf::internal::ConstantInitialized);

  inline PayloadPlayerExitZoneBegin(const PayloadPlayerExitZoneBegin& from) : PayloadPlayerExitZoneBegin(nullptr, from) {}
  inline PayloadPlayerExitZoneBegin(PayloadPlayerExitZoneBegin&& from) noexcept
      : PayloadPlayerExitZoneBegin(nullptr, ::std::move(from)) {}
  inline PayloadPlayerExitZoneBegin& operator=(const PayloadPlayerExitZoneBegin& from) {
    CopyFrom(from);
    return *this;
  }
  inline PayloadPlayerExitZoneBegin& operator=(PayloadPlayerExitZoneBegin&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PayloadPlayerExitZoneBegin& default_instance() {
    return *reinterpret_cast<const PayloadPlayerExitZoneBegin*>(
        &_PayloadPlayerExitZoneBegin_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(PayloadPlayerExitZoneBegin& a, PayloadPlayerExitZoneBegin& b) { a.Swap(&b); }
  inline void Swap(PayloadPlayerExitZoneBegin* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PayloadPlayerExitZoneBegin* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PayloadPlayerExitZoneBegin* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PayloadPlayerExitZoneBegin>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PayloadPlayerExitZoneBegin& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PayloadPlayerExitZoneBegin& from) { PayloadPlayerExitZoneBegin::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PayloadPlayerExitZoneBegin* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Proto.PayloadPlayerExitZoneBegin"; }

 protected:
  explicit PayloadPlayerExitZoneBegin(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PayloadPlayerExitZoneBegin(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadPlayerExitZoneBegin& from);
  PayloadPlayerExitZoneBegin(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PayloadPlayerExitZoneBegin&& from) noexcept
      : PayloadPlayerExitZoneBegin(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIdFieldNumber = 1,
  };
  // uint64 user_id = 1;
  void clear_user_id() ;
  ::uint64_t user_id() const;
  void set_user_id(::uint64_t value);

  private:
  ::uint64_t _internal_user_id() const;
  void _internal_set_user_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Proto.PayloadPlayerExitZoneBegin)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PayloadPlayerExitZoneBegin& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t user_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_process_2fworld_2fplayer_5froute_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerExitZoneBegin_class_data_;
// -------------------------------------------------------------------

class PayloadPlayerZoneEnterReadyResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Proto.PayloadPlayerZoneEnterReadyResponse) */ {
 public:
  inline PayloadPlayerZoneEnterReadyResponse() : PayloadPlayerZoneEnterReadyResponse(nullptr) {}
  ~PayloadPlayerZoneEnterReadyResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PayloadPlayerZoneEnterReadyResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PayloadPlayerZoneEnterReadyResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PayloadPlayerZoneEnterReadyResponse(::google::protobuf::internal::ConstantInitialized);

  inline PayloadPlayerZoneEnterReadyResponse(const PayloadPlayerZoneEnterReadyResponse& from) : PayloadPlayerZoneEnterReadyResponse(nullptr, from) {}
  inline PayloadPlayerZoneEnterReadyResponse(PayloadPlayerZoneEnterReadyResponse&& from) noexcept
      : PayloadPlayerZoneEnterReadyResponse(nullptr, ::std::move(from)) {}
  inline PayloadPlayerZoneEnterReadyResponse& operator=(const PayloadPlayerZoneEnterReadyResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PayloadPlayerZoneEnterReadyResponse& operator=(PayloadPlayerZoneEnterReadyResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PayloadPlayerZoneEnterReadyResponse& default_instance() {
    return *reinterpret_cast<const PayloadPlayerZoneEnterReadyResponse*>(
        &_PayloadPlayerZoneEnterReadyResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(PayloadPlayerZoneEnterReadyResponse& a, PayloadPlayerZoneEnterReadyResponse& b) { a.Swap(&b); }
  inline void Swap(PayloadPlayerZoneEnterReadyResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PayloadPlayerZoneEnterReadyResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PayloadPlayerZoneEnterReadyResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PayloadPlayerZoneEnterReadyResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PayloadPlayerZoneEnterReadyResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PayloadPlayerZoneEnterReadyResponse& from) { PayloadPlayerZoneEnterReadyResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PayloadPlayerZoneEnterReadyResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Proto.PayloadPlayerZoneEnterReadyResponse"; }

 protected:
  explicit PayloadPlayerZoneEnterReadyResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PayloadPlayerZoneEnterReadyResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PayloadPlayerZoneEnterReadyResponse& from);
  PayloadPlayerZoneEnterReadyResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PayloadPlayerZoneEnterReadyResponse&& from) noexcept
      : PayloadPlayerZoneEnterReadyResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlayerDataFieldNumber = 1,
  };
  // optional .Proto.RoutePlayerData player_data = 1;
  bool has_player_data() const;
  void clear_player_data() ;
  const ::Proto::RoutePlayerData& player_data() const;
  [[nodiscard]] ::Proto::RoutePlayerData* PROTOBUF_NULLABLE release_player_data();
  ::Proto::RoutePlayerData* PROTOBUF_NONNULL mutable_player_data();
  void set_allocated_player_data(::Proto::RoutePlayerData* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_player_data(::Proto::RoutePlayerData* PROTOBUF_NULLABLE value);
  ::Proto::RoutePlayerData* PROTOBUF_NULLABLE unsafe_arena_release_player_data();

  private:
  const ::Proto::RoutePlayerData& _internal_player_data() const;
  ::Proto::RoutePlayerData* PROTOBUF_NONNULL _internal_mutable_player_data();

  public:
  // @@protoc_insertion_point(class_scope:Proto.PayloadPlayerZoneEnterReadyResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PayloadPlayerZoneEnterReadyResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Proto::RoutePlayerData* PROTOBUF_NULLABLE player_data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_process_2fworld_2fplayer_5froute_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PayloadPlayerZoneEnterReadyResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PayloadPlayerZoneEnterBegin

// uint64 user_id = 1;
inline void PayloadPlayerZoneEnterBegin::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::uint64_t PayloadPlayerZoneEnterBegin::user_id() const {
  // @@protoc_insertion_point(field_get:Proto.PayloadPlayerZoneEnterBegin.user_id)
  return _internal_user_id();
}
inline void PayloadPlayerZoneEnterBegin::set_user_id(::uint64_t value) {
  _internal_set_user_id(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:Proto.PayloadPlayerZoneEnterBegin.user_id)
}
inline ::uint64_t PayloadPlayerZoneEnterBegin::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_;
}
inline void PayloadPlayerZoneEnterBegin::_internal_set_user_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = value;
}

// uint64 gateway_id = 2;
inline void PayloadPlayerZoneEnterBegin::clear_gateway_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gateway_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint64_t PayloadPlayerZoneEnterBegin::gateway_id() const {
  // @@protoc_insertion_point(field_get:Proto.PayloadPlayerZoneEnterBegin.gateway_id)
  return _internal_gateway_id();
}
inline void PayloadPlayerZoneEnterBegin::set_gateway_id(::uint64_t value) {
  _internal_set_gateway_id(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:Proto.PayloadPlayerZoneEnterBegin.gateway_id)
}
inline ::uint64_t PayloadPlayerZoneEnterBegin::_internal_gateway_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gateway_id_;
}
inline void PayloadPlayerZoneEnterBegin::_internal_set_gateway_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gateway_id_ = value;
}

// -------------------------------------------------------------------

// PayloadPlayerZoneEnterReady

// uint64 user_id = 1;
inline void PayloadPlayerZoneEnterReady::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::uint64_t PayloadPlayerZoneEnterReady::user_id() const {
  // @@protoc_insertion_point(field_get:Proto.PayloadPlayerZoneEnterReady.user_id)
  return _internal_user_id();
}
inline void PayloadPlayerZoneEnterReady::set_user_id(::uint64_t value) {
  _internal_set_user_id(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:Proto.PayloadPlayerZoneEnterReady.user_id)
}
inline ::uint64_t PayloadPlayerZoneEnterReady::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_;
}
inline void PayloadPlayerZoneEnterReady::_internal_set_user_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = value;
}

// -------------------------------------------------------------------

// PayloadPlayerZoneEnterComplete

// uint64 user_id = 1;
inline void PayloadPlayerZoneEnterComplete::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::uint64_t PayloadPlayerZoneEnterComplete::user_id() const {
  // @@protoc_insertion_point(field_get:Proto.PayloadPlayerZoneEnterComplete.user_id)
  return _internal_user_id();
}
inline void PayloadPlayerZoneEnterComplete::set_user_id(::uint64_t value) {
  _internal_set_user_id(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:Proto.PayloadPlayerZoneEnterComplete.user_id)
}
inline ::uint64_t PayloadPlayerZoneEnterComplete::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_;
}
inline void PayloadPlayerZoneEnterComplete::_internal_set_user_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = value;
}

// -------------------------------------------------------------------

// PayloadPlayerZoneEnterReadyResponse

// optional .Proto.RoutePlayerData player_data = 1;
inline bool PayloadPlayerZoneEnterReadyResponse::has_player_data() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.player_data_ != nullptr);
  return value;
}
inline const ::Proto::RoutePlayerData& PayloadPlayerZoneEnterReadyResponse::_internal_player_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Proto::RoutePlayerData* p = _impl_.player_data_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::RoutePlayerData&>(::Proto::_RoutePlayerData_default_instance_);
}
inline const ::Proto::RoutePlayerData& PayloadPlayerZoneEnterReadyResponse::player_data() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Proto.PayloadPlayerZoneEnterReadyResponse.player_data)
  return _internal_player_data();
}
inline void PayloadPlayerZoneEnterReadyResponse::unsafe_arena_set_allocated_player_data(
    ::Proto::RoutePlayerData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.player_data_);
  }
  _impl_.player_data_ = reinterpret_cast<::Proto::RoutePlayerData*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.PayloadPlayerZoneEnterReadyResponse.player_data)
}
inline ::Proto::RoutePlayerData* PROTOBUF_NULLABLE PayloadPlayerZoneEnterReadyResponse::release_player_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::Proto::RoutePlayerData* released = _impl_.player_data_;
  _impl_.player_data_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Proto::RoutePlayerData* PROTOBUF_NULLABLE PayloadPlayerZoneEnterReadyResponse::unsafe_arena_release_player_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Proto.PayloadPlayerZoneEnterReadyResponse.player_data)

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::Proto::RoutePlayerData* temp = _impl_.player_data_;
  _impl_.player_data_ = nullptr;
  return temp;
}
inline ::Proto::RoutePlayerData* PROTOBUF_NONNULL PayloadPlayerZoneEnterReadyResponse::_internal_mutable_player_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.player_data_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Proto::RoutePlayerData>(GetArena());
    _impl_.player_data_ = reinterpret_cast<::Proto::RoutePlayerData*>(p);
  }
  return _impl_.player_data_;
}
inline ::Proto::RoutePlayerData* PROTOBUF_NONNULL PayloadPlayerZoneEnterReadyResponse::mutable_player_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001U;
  ::Proto::RoutePlayerData* _msg = _internal_mutable_player_data();
  // @@protoc_insertion_point(field_mutable:Proto.PayloadPlayerZoneEnterReadyResponse.player_data)
  return _msg;
}
inline void PayloadPlayerZoneEnterReadyResponse::set_allocated_player_data(::Proto::RoutePlayerData* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.player_data_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }

  _impl_.player_data_ = reinterpret_cast<::Proto::RoutePlayerData*>(value);
  // @@protoc_insertion_point(field_set_allocated:Proto.PayloadPlayerZoneEnterReadyResponse.player_data)
}

// -------------------------------------------------------------------

// PayloadPlayerExitZoneBegin

// uint64 user_id = 1;
inline void PayloadPlayerExitZoneBegin::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::uint64_t PayloadPlayerExitZoneBegin::user_id() const {
  // @@protoc_insertion_point(field_get:Proto.PayloadPlayerExitZoneBegin.user_id)
  return _internal_user_id();
}
inline void PayloadPlayerExitZoneBegin::set_user_id(::uint64_t value) {
  _internal_set_user_id(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:Proto.PayloadPlayerExitZoneBegin.user_id)
}
inline ::uint64_t PayloadPlayerExitZoneBegin::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_;
}
inline void PayloadPlayerExitZoneBegin::_internal_set_user_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = value;
}

// -------------------------------------------------------------------

// PayloadPlayerExitZoneReady

// uint64 user_id = 1;
inline void PayloadPlayerExitZoneReady::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::uint64_t PayloadPlayerExitZoneReady::user_id() const {
  // @@protoc_insertion_point(field_get:Proto.PayloadPlayerExitZoneReady.user_id)
  return _internal_user_id();
}
inline void PayloadPlayerExitZoneReady::set_user_id(::uint64_t value) {
  _internal_set_user_id(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:Proto.PayloadPlayerExitZoneReady.user_id)
}
inline ::uint64_t PayloadPlayerExitZoneReady::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_;
}
inline void PayloadPlayerExitZoneReady::_internal_set_user_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = value;
}

// -------------------------------------------------------------------

// PayloadPlayerExitZoneComplete

// uint64 user_id = 1;
inline void PayloadPlayerExitZoneComplete::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::uint64_t PayloadPlayerExitZoneComplete::user_id() const {
  // @@protoc_insertion_point(field_get:Proto.PayloadPlayerExitZoneComplete.user_id)
  return _internal_user_id();
}
inline void PayloadPlayerExitZoneComplete::set_user_id(::uint64_t value) {
  _internal_set_user_id(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:Proto.PayloadPlayerExitZoneComplete.user_id)
}
inline ::uint64_t PayloadPlayerExitZoneComplete::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_;
}
inline void PayloadPlayerExitZoneComplete::_internal_set_user_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // process_2fworld_2fplayer_5froute_2eproto_2epb_2eh
