// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/world/route_player_data.proto
// Protobuf C++ Version: 6.32.1

#ifndef process_2fworld_2froute_5fplayer_5fdata_2eproto_2epb_2eh
#define process_2fworld_2froute_5fplayer_5fdata_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "common/math.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_process_2fworld_2froute_5fplayer_5fdata_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_process_2fworld_2froute_5fplayer_5fdata_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_process_2fworld_2froute_5fplayer_5fdata_2eproto;
}  // extern "C"
namespace Proto {
class RoutePlayerData;
struct RoutePlayerDataDefaultTypeInternal;
extern RoutePlayerDataDefaultTypeInternal _RoutePlayerData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RoutePlayerData_class_data_;
}  // namespace Proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Proto {

// ===================================================================


// -------------------------------------------------------------------

class RoutePlayerData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Proto.RoutePlayerData) */ {
 public:
  inline RoutePlayerData() : RoutePlayerData(nullptr) {}
  ~RoutePlayerData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RoutePlayerData* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RoutePlayerData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RoutePlayerData(::google::protobuf::internal::ConstantInitialized);

  inline RoutePlayerData(const RoutePlayerData& from) : RoutePlayerData(nullptr, from) {}
  inline RoutePlayerData(RoutePlayerData&& from) noexcept
      : RoutePlayerData(nullptr, ::std::move(from)) {}
  inline RoutePlayerData& operator=(const RoutePlayerData& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoutePlayerData& operator=(RoutePlayerData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoutePlayerData& default_instance() {
    return *reinterpret_cast<const RoutePlayerData*>(
        &_RoutePlayerData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RoutePlayerData& a, RoutePlayerData& b) { a.Swap(&b); }
  inline void Swap(RoutePlayerData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoutePlayerData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoutePlayerData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RoutePlayerData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RoutePlayerData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RoutePlayerData& from) { RoutePlayerData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RoutePlayerData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Proto.RoutePlayerData"; }

 protected:
  explicit RoutePlayerData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RoutePlayerData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RoutePlayerData& from);
  RoutePlayerData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RoutePlayerData&& from) noexcept
      : RoutePlayerData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPositionFieldNumber = 2,
    kPlayerEntityIdFieldNumber = 1,
  };
  // .Proto.Vector3 position = 2;
  bool has_position() const;
  void clear_position() ;
  const ::Proto::Vector3& position() const;
  [[nodiscard]] ::Proto::Vector3* PROTOBUF_NULLABLE release_position();
  ::Proto::Vector3* PROTOBUF_NONNULL mutable_position();
  void set_allocated_position(::Proto::Vector3* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_position(::Proto::Vector3* PROTOBUF_NULLABLE value);
  ::Proto::Vector3* PROTOBUF_NULLABLE unsafe_arena_release_position();

  private:
  const ::Proto::Vector3& _internal_position() const;
  ::Proto::Vector3* PROTOBUF_NONNULL _internal_mutable_position();

  public:
  // uint64 player_entity_id = 1;
  void clear_player_entity_id() ;
  ::uint64_t player_entity_id() const;
  void set_player_entity_id(::uint64_t value);

  private:
  ::uint64_t _internal_player_entity_id() const;
  void _internal_set_player_entity_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Proto.RoutePlayerData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RoutePlayerData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Proto::Vector3* PROTOBUF_NULLABLE position_;
    ::uint64_t player_entity_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_process_2fworld_2froute_5fplayer_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RoutePlayerData_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RoutePlayerData

// uint64 player_entity_id = 1;
inline void RoutePlayerData::clear_player_entity_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_entity_id_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint64_t RoutePlayerData::player_entity_id() const {
  // @@protoc_insertion_point(field_get:Proto.RoutePlayerData.player_entity_id)
  return _internal_player_entity_id();
}
inline void RoutePlayerData::set_player_entity_id(::uint64_t value) {
  _internal_set_player_entity_id(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:Proto.RoutePlayerData.player_entity_id)
}
inline ::uint64_t RoutePlayerData::_internal_player_entity_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.player_entity_id_;
}
inline void RoutePlayerData::_internal_set_player_entity_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_entity_id_ = value;
}

// .Proto.Vector3 position = 2;
inline bool RoutePlayerData::has_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.position_ != nullptr);
  return value;
}
inline const ::Proto::Vector3& RoutePlayerData::_internal_position() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Proto::Vector3* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Proto::Vector3&>(::Proto::_Vector3_default_instance_);
}
inline const ::Proto::Vector3& RoutePlayerData::position() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Proto.RoutePlayerData.position)
  return _internal_position();
}
inline void RoutePlayerData::unsafe_arena_set_allocated_position(
    ::Proto::Vector3* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = reinterpret_cast<::Proto::Vector3*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Proto.RoutePlayerData.position)
}
inline ::Proto::Vector3* PROTOBUF_NULLABLE RoutePlayerData::release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::Proto::Vector3* released = _impl_.position_;
  _impl_.position_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Proto::Vector3* PROTOBUF_NULLABLE RoutePlayerData::unsafe_arena_release_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Proto.RoutePlayerData.position)

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::Proto::Vector3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::Proto::Vector3* PROTOBUF_NONNULL RoutePlayerData::_internal_mutable_position() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.position_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Proto::Vector3>(GetArena());
    _impl_.position_ = reinterpret_cast<::Proto::Vector3*>(p);
  }
  return _impl_.position_;
}
inline ::Proto::Vector3* PROTOBUF_NONNULL RoutePlayerData::mutable_position()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001U;
  ::Proto::Vector3* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:Proto.RoutePlayerData.position)
  return _msg;
}
inline void RoutePlayerData::set_allocated_position(::Proto::Vector3* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.position_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }

  _impl_.position_ = reinterpret_cast<::Proto::Vector3*>(value);
  // @@protoc_insertion_point(field_set_allocated:Proto.RoutePlayerData.position)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // process_2fworld_2froute_5fplayer_5fdata_2eproto_2epb_2eh
