// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: process/db/user/signup.proto
// Protobuf C++ Version: 6.32.1

#include "process/db/user/signup.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Proto {

inline constexpr PayloadSignupRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        username_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR PayloadSignupRequest::PayloadSignupRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PayloadSignupRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PayloadSignupRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadSignupRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadSignupRequestDefaultTypeInternal() {}
  union {
    PayloadSignupRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadSignupRequestDefaultTypeInternal _PayloadSignupRequest_default_instance_;

inline constexpr PayloadSignupResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        session_id_{nullptr},
        user_id_{::uint64_t{0u}},
        is_succeeded_{false} {}

template <typename>
PROTOBUF_CONSTEXPR PayloadSignupResponse::PayloadSignupResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PayloadSignupResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PayloadSignupResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadSignupResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadSignupResponseDefaultTypeInternal() {}
  union {
    PayloadSignupResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadSignupResponseDefaultTypeInternal _PayloadSignupResponse_default_instance_;
}  // namespace Proto
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_process_2fdb_2fuser_2fsignup_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_process_2fdb_2fuser_2fsignup_2eproto = nullptr;
const ::uint32_t
    TableStruct_process_2fdb_2fuser_2fsignup_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadSignupRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadSignupRequest, _impl_.username_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadSignupResponse, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadSignupResponse, _impl_.is_succeeded_),
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadSignupResponse, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::Proto::PayloadSignupResponse, _impl_.session_id_),
        2,
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::Proto::PayloadSignupRequest)},
        {5, sizeof(::Proto::PayloadSignupResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::Proto::_PayloadSignupRequest_default_instance_._instance,
    &::Proto::_PayloadSignupResponse_default_instance_._instance,
};
const char descriptor_table_protodef_process_2fdb_2fuser_2fsignup_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\034process/db/user/signup.proto\022\005Proto\032\024c"
    "ommon/session.proto\"(\n\024PayloadSignupRequ"
    "est\022\020\n\010username\030\001 \001(\t\"d\n\025PayloadSignupRe"
    "sponse\022\024\n\014is_succeeded\030\001 \001(\010\022\017\n\007user_id\030"
    "\002 \001(\004\022$\n\nsession_id\030\003 \001(\0132\020.Proto.Sessio"
    "nIdb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_process_2fdb_2fuser_2fsignup_2eproto_deps[1] = {
        &::descriptor_table_common_2fsession_2eproto,
};
static ::absl::once_flag descriptor_table_process_2fdb_2fuser_2fsignup_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_process_2fdb_2fuser_2fsignup_2eproto = {
    false,
    false,
    211,
    descriptor_table_protodef_process_2fdb_2fuser_2fsignup_2eproto,
    "process/db/user/signup.proto",
    &descriptor_table_process_2fdb_2fuser_2fsignup_2eproto_once,
    descriptor_table_process_2fdb_2fuser_2fsignup_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_process_2fdb_2fuser_2fsignup_2eproto::offsets,
    file_level_enum_descriptors_process_2fdb_2fuser_2fsignup_2eproto,
    file_level_service_descriptors_process_2fdb_2fuser_2fsignup_2eproto,
};
namespace Proto {
// ===================================================================

class PayloadSignupRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PayloadSignupRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PayloadSignupRequest, _impl_._has_bits_);
};

PayloadSignupRequest::PayloadSignupRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadSignupRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.PayloadSignupRequest)
}
PROTOBUF_NDEBUG_INLINE PayloadSignupRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Proto::PayloadSignupRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        username_(arena, from.username_) {}

PayloadSignupRequest::PayloadSignupRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PayloadSignupRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadSignupRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PayloadSignupRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Proto.PayloadSignupRequest)
}
PROTOBUF_NDEBUG_INLINE PayloadSignupRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        username_(arena) {}

inline void PayloadSignupRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PayloadSignupRequest::~PayloadSignupRequest() {
  // @@protoc_insertion_point(destructor:Proto.PayloadSignupRequest)
  SharedDtor(*this);
}
inline void PayloadSignupRequest::SharedDtor(MessageLite& self) {
  PayloadSignupRequest& this_ = static_cast<PayloadSignupRequest&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.username_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PayloadSignupRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PayloadSignupRequest(arena);
}
constexpr auto PayloadSignupRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PayloadSignupRequest),
                                            alignof(PayloadSignupRequest));
}
constexpr auto PayloadSignupRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PayloadSignupRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PayloadSignupRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PayloadSignupRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PayloadSignupRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PayloadSignupRequest>(), &PayloadSignupRequest::ByteSizeLong,
              &PayloadSignupRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PayloadSignupRequest, _impl_._cached_size_),
          false,
      },
      &PayloadSignupRequest::kDescriptorMethods,
      &descriptor_table_process_2fdb_2fuser_2fsignup_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PayloadSignupRequest_class_data_ =
        PayloadSignupRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PayloadSignupRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PayloadSignupRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PayloadSignupRequest_class_data_.tc_table);
  return PayloadSignupRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 43, 2>
PayloadSignupRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PayloadSignupRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PayloadSignupRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::PayloadSignupRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string username = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(PayloadSignupRequest, _impl_.username_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string username = 1;
    {PROTOBUF_FIELD_OFFSET(PayloadSignupRequest, _impl_.username_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\10\0\0\0\0\0\0"
    "Proto.PayloadSignupRequest"
    "username"
  }},
};
PROTOBUF_NOINLINE void PayloadSignupRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.PayloadSignupRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.username_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PayloadSignupRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PayloadSignupRequest& this_ = static_cast<const PayloadSignupRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PayloadSignupRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PayloadSignupRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.PayloadSignupRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string username = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (!this_._internal_username().empty()) {
      const ::std::string& _s = this_._internal_username();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Proto.PayloadSignupRequest.username");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.PayloadSignupRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PayloadSignupRequest::ByteSizeLong(const MessageLite& base) {
  const PayloadSignupRequest& this_ = static_cast<const PayloadSignupRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PayloadSignupRequest::ByteSizeLong() const {
  const PayloadSignupRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.PayloadSignupRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string username = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (!this_._internal_username().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_username());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PayloadSignupRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PayloadSignupRequest*>(&to_msg);
  auto& from = static_cast<const PayloadSignupRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.PayloadSignupRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (!from._internal_username().empty()) {
      _this->_internal_set_username(from._internal_username());
    } else {
      if (_this->_impl_.username_.IsDefault()) {
        _this->_internal_set_username("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadSignupRequest::CopyFrom(const PayloadSignupRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.PayloadSignupRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PayloadSignupRequest::InternalSwap(PayloadSignupRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.username_, &other->_impl_.username_, arena);
}

::google::protobuf::Metadata PayloadSignupRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PayloadSignupResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PayloadSignupResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PayloadSignupResponse, _impl_._has_bits_);
};

void PayloadSignupResponse::clear_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.session_id_ != nullptr) _impl_.session_id_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
PayloadSignupResponse::PayloadSignupResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadSignupResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Proto.PayloadSignupResponse)
}
PROTOBUF_NDEBUG_INLINE PayloadSignupResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Proto::PayloadSignupResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

PayloadSignupResponse::PayloadSignupResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PayloadSignupResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PayloadSignupResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PayloadSignupResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.session_id_ = ((cached_has_bits & 0x00000001U) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.session_id_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, user_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, user_id_),
           offsetof(Impl_, is_succeeded_) -
               offsetof(Impl_, user_id_) +
               sizeof(Impl_::is_succeeded_));

  // @@protoc_insertion_point(copy_constructor:Proto.PayloadSignupResponse)
}
PROTOBUF_NDEBUG_INLINE PayloadSignupResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PayloadSignupResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, session_id_),
           0,
           offsetof(Impl_, is_succeeded_) -
               offsetof(Impl_, session_id_) +
               sizeof(Impl_::is_succeeded_));
}
PayloadSignupResponse::~PayloadSignupResponse() {
  // @@protoc_insertion_point(destructor:Proto.PayloadSignupResponse)
  SharedDtor(*this);
}
inline void PayloadSignupResponse::SharedDtor(MessageLite& self) {
  PayloadSignupResponse& this_ = static_cast<PayloadSignupResponse&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.session_id_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PayloadSignupResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PayloadSignupResponse(arena);
}
constexpr auto PayloadSignupResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PayloadSignupResponse),
                                            alignof(PayloadSignupResponse));
}
constexpr auto PayloadSignupResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PayloadSignupResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PayloadSignupResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PayloadSignupResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PayloadSignupResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PayloadSignupResponse>(), &PayloadSignupResponse::ByteSizeLong,
              &PayloadSignupResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PayloadSignupResponse, _impl_._cached_size_),
          false,
      },
      &PayloadSignupResponse::kDescriptorMethods,
      &descriptor_table_process_2fdb_2fuser_2fsignup_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PayloadSignupResponse_class_data_ =
        PayloadSignupResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PayloadSignupResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PayloadSignupResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PayloadSignupResponse_class_data_.tc_table);
  return PayloadSignupResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2>
PayloadSignupResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PayloadSignupResponse, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PayloadSignupResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Proto::PayloadSignupResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool is_succeeded = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PayloadSignupResponse, _impl_.is_succeeded_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(PayloadSignupResponse, _impl_.is_succeeded_)}},
    // uint64 user_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PayloadSignupResponse, _impl_.user_id_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(PayloadSignupResponse, _impl_.user_id_)}},
    // .Proto.SessionId session_id = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(PayloadSignupResponse, _impl_.session_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool is_succeeded = 1;
    {PROTOBUF_FIELD_OFFSET(PayloadSignupResponse, _impl_.is_succeeded_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // uint64 user_id = 2;
    {PROTOBUF_FIELD_OFFSET(PayloadSignupResponse, _impl_.user_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // .Proto.SessionId session_id = 3;
    {PROTOBUF_FIELD_OFFSET(PayloadSignupResponse, _impl_.session_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::Proto::SessionId>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void PayloadSignupResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.PayloadSignupResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    ABSL_DCHECK(_impl_.session_id_ != nullptr);
    _impl_.session_id_->Clear();
  }
  if ((cached_has_bits & 0x00000006U) != 0) {
    ::memset(&_impl_.user_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.is_succeeded_) -
        reinterpret_cast<char*>(&_impl_.user_id_)) + sizeof(_impl_.is_succeeded_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PayloadSignupResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PayloadSignupResponse& this_ = static_cast<const PayloadSignupResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PayloadSignupResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PayloadSignupResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Proto.PayloadSignupResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool is_succeeded = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000004U) != 0) {
    if (this_._internal_is_succeeded() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_is_succeeded(), target);
    }
  }

  // uint64 user_id = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (this_._internal_user_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_user_id(), target);
    }
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // .Proto.SessionId session_id = 3;
  if ((cached_has_bits & 0x00000001U) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.session_id_, this_._impl_.session_id_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.PayloadSignupResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PayloadSignupResponse::ByteSizeLong(const MessageLite& base) {
  const PayloadSignupResponse& this_ = static_cast<const PayloadSignupResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PayloadSignupResponse::ByteSizeLong() const {
  const PayloadSignupResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Proto.PayloadSignupResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    // .Proto.SessionId session_id = 3;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.session_id_);
    }
    // uint64 user_id = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (this_._internal_user_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_user_id());
      }
    }
    // bool is_succeeded = 1;
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (this_._internal_is_succeeded() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PayloadSignupResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PayloadSignupResponse*>(&to_msg);
  auto& from = static_cast<const PayloadSignupResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.PayloadSignupResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      ABSL_DCHECK(from._impl_.session_id_ != nullptr);
      if (_this->_impl_.session_id_ == nullptr) {
        _this->_impl_.session_id_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.session_id_);
      } else {
        _this->_impl_.session_id_->MergeFrom(*from._impl_.session_id_);
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (from._internal_user_id() != 0) {
        _this->_impl_.user_id_ = from._impl_.user_id_;
      }
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (from._internal_is_succeeded() != 0) {
        _this->_impl_.is_succeeded_ = from._impl_.is_succeeded_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadSignupResponse::CopyFrom(const PayloadSignupResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.PayloadSignupResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PayloadSignupResponse::InternalSwap(PayloadSignupResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PayloadSignupResponse, _impl_.is_succeeded_)
      + sizeof(PayloadSignupResponse::_impl_.is_succeeded_)
      - PROTOBUF_FIELD_OFFSET(PayloadSignupResponse, _impl_.session_id_)>(
          reinterpret_cast<char*>(&_impl_.session_id_),
          reinterpret_cast<char*>(&other->_impl_.session_id_));
}

::google::protobuf::Metadata PayloadSignupResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_process_2fdb_2fuser_2fsignup_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
